### ISSUE TITLE
Export failed on Android

### ISSUE THREAD

**Issue by hjyoung1** [alexhua/Aria2-for-chrome#1]
Hello thank you so much for your extension.
I know it's made for chrome pc users 
But I'm using it on Android yandex browser supports chrome extension. 
But whenever i try to download using context menu i always get task failed. 
Check screenshots I'm attaching. 
![Screenshot_20190519-022523](https://user-images.githubusercontent.com/45882061/57975254-07fbf280-79e3-11e9-8714-22849b0f5120.png)

Adding link manually works fine. 

![Screenshot_20190519-025444](https://user-images.githubusercontent.com/45882061/57975257-15b17800-79e3-11e9-996a-efe5c7f13d35.png)

Browser :-  https://play.google.com/store/apps/details?id=com.yandex.browser

Aria2 server :- https://play.google.com/store/apps/details?id=com.gianlu.aria2android

**Comment by hjyoung1** [comment]
Issue was with aria2 server. Tried aria2 server using termux export working now.

**Comment by lvv9** [comment]
谢谢这位兄弟，原来还有这种浏览器。
