### ISSUE TITLE
请求重新置顶 #17 issue

### ISSUE THREAD

**Issue by Pr0pHesyer** [alexhua/Aria2-for-chrome#100]
**Describe the bug**
在我的windows 11操作系统上，使用aria2-1.36.0-win-64bit-build1 搭配 Aria2 for Chrome 1.5.7  ，依然出现如 #17 中所出现的问题而无法使用密钥

**To Reproduce**
配置rpc-secret后进行一个下载便可出现带有Error:Unauthorized的通知

**Expected behavior**
出现带有Error:Unauthorized的通知

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Chrome
 - Version 1.5.7

**Additional context**
之前置顶了，为什么后来又取消置顶了呢？你也没修啊（

**Comment by alexhua** [comment]
能想着去搜下以前的问题，习惯不错。不过需要你再看仔细点，根本就不是一个问题，况且 #17 也不是Bug。
你这提示说明你在 chrome-extension://mpkodccbngfoacfalldjimigbofkhgjn/options.html 的secretkey没填对。
先检查一下吧

**Comment by Pr0pHesyer** [comment]
> 能想着去搜下以前的问题，习惯不错。不过需要你再看仔细点，根本就不是一个问题，况且 #17 也不是Bug。 你这提示说明你在 chrome-extension://mpkodccbngfoacfalldjimigbofkhgjn/options.html 的secretkey没填对。 先检查一下吧

密码确实是填对了的。
而 #17 反应的也不是密码问题，而是要添加token字段。如果我直接按照面板输入后保存刷新，再次下载时是会出现错误的。
这个插件是基于那个Web UI的，要抓log也是挺难的。

**Comment by alexhua** [comment]
> 密码确实是填对了的。 而 #17 反应的也不是密码问题，而是要添加token字段。
都更新多少版本了，早都不需要加token字段了，直接填Secret Key就行。
给你两个方法定位一下问题：
1. 配置一个纯数字的密码重连试试。
2. 打开扩展内置的AriaNG配置一下RPC，看看AriaNG能否正常连接。
如果纯数字密码或者AriaNG能连通说明确实有Bug。

**Comment by alexhua** [comment]
> 密码确实是填对了的。 而 #17 反应的也不是密码问题，而是要添加token字段。
都更新多少版本了，早都不需要加token字段了，直接填Secret Key就行。
给你两个方法定位一下问题：
1. 配置一个纯数字的密码重连试试。
2. 打开扩展内置的AriaNG配置一下RPC，看看AriaNG能否正常连接。
如果纯数字密码或者AriaNG能连通说明确实有Bug。

**Comment by Pr0pHesyer** [comment]
> > 密码确实是填对了的。 而 #17 反应的也不是密码问题，而是要添加token字段。
> 
> 都更新多少版本了，早都不需要加token字段了，直接填Secret Key就行。 给你两个方法定位一下问题：
> 
> 1. 配置一个纯数字的密码重连试试。
> 2. 打开扩展内置的AriaNG配置一下RPC，看看AriaNG能否正常连接。
>    如果纯数字密码或者AriaNG能连通说明确实有Bug。

又能用了...只能说有点玄学...

**Comment by alexhua** [comment]
> 又能用了...只能说有点玄学...
计算机世界不存在玄学，所以请在报Bug之前请先确认确实个软件的Bug

**Comment by Pr0pHesyer** [comment]
> > 又能用了...只能说有点玄学...
> > 计算机世界不存在玄学，所以请在报Bug之前先确认确实是软件的Bug



> > 又能用了...只能说有点玄学...
> > 计算机世界不存在玄学，所以请在报Bug之前先确认确实是软件的Bug

没log呀…下次我拿不同前端试试吧
