### ISSUE TITLE
下载拦截无法使用aria2c的config文件位置

### ISSUE THREAD

**Issue by WeiYiAcc** [alexhua/Aria2-for-chrome#102]
文件下载路径设为"E:\home\weiyiacc\Downloads\"，如果不勾选：下载拦截——自动下载前询问参数设置，下载的文件会出现在默认的aria2c的home目录"C:\Users\Administrator\XXX\"下面，我使用的scoop的aria2c。
如果使用Motrix，那么文件会出现在'C:\Windows\SysWOW64\xxx\',我怀疑此时我在本地文件设置的代理参数等都是失效的。
Chrome版本 104.0.5112.81（正式版本） （64 位）

**Comment by alexhua** [comment]
可能因为你的扩展配置里 Aria2 RPC 项的`Download Location`是空的，会覆盖掉本地aria2 config的 dir配置
Download Location 填为你想要的目录就好了。

**Comment by WeiYiAcc** [comment]
算了，打开自动下载前询问参数设置这个选项吧，多点一下鼠标吧，不折腾了，
