### ISSUE TITLE
Restore Download History

### ISSUE THREAD

**Issue by AxoCode** [alexhua/Aria2-for-chrome#105]
**Motivation**
When I open the browser after closing it, All the downloading/waiting/finished just gone.

**Feature Description**
Restore back all the downloads. And if you close the browser when downloading it will be paused (Waiting) and can be resumed when opening the browser back

**Is the solution code ready**
No

**Willing to maintain the related code in the future**
No

**Additional context**
If you use a Download Manager before, you know that you can resume download even after you shut down the PC. But here (currently), you cannot resume the download, but instead you have to go to that download link again to continue the download

**Comment by alexhua** [comment]
It's the aria2c's obiligation to save the task info. You could switch on the --save-session --input-file option of your aria2c. 
Reference: http://aria2.github.io/manual/en/html/aria2c.html#cmdoption-save-session
