### ISSUE TITLE
关于 URL Pattern的补充说明。

### ISSUE THREAD

**Issue by makeye** [alexhua/Aria2-for-chrome#107]
关于这个我还是没看懂，看到你讨论的意思是把这个多的rpc服务器后面参数填需要下载的类型就行了吗？具体咋设置麻烦讲一下，希望这个功能能改进下，改成可以添加多个服务器，然后下载东西的时候能够选择一下。感觉这样还是好麻烦（关于 URL Pattern）

**Comment by alexhua** [comment]
想手动选RPC服务器，就在AriaNG里多设置几个RPC地址，并且勾选“下载前询问详细设置”，然后下载时在AriaNG的左上角切换RPC，如下图：

`注意： 目前扩展的RPC设置和AriaNG相对独立，设置扩展RPC时，只会单向同步默认（或第一个）RPC设置到AriaNG`
![手动选择 RPC](https://user-images.githubusercontent.com/1220458/196042654-8f01741a-4660-4271-9127-036bbc62d9af.png)

---
想根据下载内容的URL地址或类型自动选择RPC服务器，就在扩展页面RPC 条目的 URL Pattern项填上相应的pattern，并且取消勾选“下载前询问详细设置”。`（注：需要你有一点正则表达式和字符串匹配的相关知识）`

每次拦截，扩展会把下载地址和每一个RPC Server 的URL Pattern进行匹配，匹配成功就选择相应的RPC Server，不成功就选择默认（或第一个）RPC Server自动进行下载。

如下图，这个例子实现了把mp4 mkv torrent 文件自动下载到`E:\Videos`这个地址。因为如果下载地址以mp4, mkv或者torrent结尾，就符合第二项RPC Server的URL pattern，扩展就会选择第二个RPC Server进行下载。

![自动选择](https://user-images.githubusercontent.com/1220458/130556178-d2f78b83-3b12-41ff-99ce-d4ea98260b91.png)

好了我觉得说得够清楚了，这是个比较高级的用法，其他要靠你多用和多悟了，普通用户建议直接忽略。

**Comment by marslulu** [comment]
大神好，我的问题跟这里的情况类似，就不再另起帖子提问了。目前我遇到的问题是，一个torrent下载任务中，包含了太多杂七杂八的垃圾文件，我想只下载其中指定后缀名的文件，且要控制文件大小不小于设定值，不知道能否通过RPC-server的URL Pattern来实现？
比如，下载条件为：文件大小≥200M，且后缀名为.mp4或.avi或.ts
谢谢啦！

**Comment by alexhua** [comment]
不能，`URL Pattern`只能匹配下载地址，种子里的文件需要靠你，手动去AriaNG下载任务的`文件列表`里去选。
进一步的需求你可以提给[AriaNG](https://github.com/mayswind/ariaNG/issues)

**Comment by marslulu** [comment]
好的，谢谢啦！
