### ISSUE TITLE
希望可以调整弹窗模式的窗口大小

### ISSUE THREAD

**Issue by CCCAUCHY** [alexhua/Aria2-for-chrome#109]
新版ariaNG的UI元素都变大了不少，希望可以适配一下，或者请求移动模板。最好能够让用户自己调整大小，不要求可以用鼠标拉大，给个选项填写也可以

**Is the solution code ready**
 No

**Willing to maintain the related code in the future**
 No

而且原版没有左侧菜单栏插件版
![image](https://user-images.githubusercontent.com/55306290/203583187-941a72dd-b42a-4fa8-a876-df80b9386588.png)

而且插件版点击“切换导航”按钮出来的菜单点击了什么也不会发生，位置也是错位的
![image](https://user-images.githubusercontent.com/55306290/203583965-3c25eb20-e15e-4300-95d2-7f132f55157b.png)

**Comment by CCCAUCHY** [comment]
> 你选的是弹窗模式吧，Chrome有限制，弹窗模式窗口大小已经是极限了。
> 
> 这次升级了AriaNG的底层框架，弹窗模式下的导航条做了一些改动，至于要不要显示迷你导航条见仁见智，需要你适应一下。后续也可能加个选项让用户选择。
> 
> 左侧导航条，确实有点宽，我看看后续能不能调整一下。
> 
> 你也可以试试”新窗口“模式，比弹窗模式舒服得多。

还是去掉迷你导航条吧，新窗口模式虽然可以召之即来，但是不能挥之即去，只能点击右上角的X关闭

**Comment by alexhua** [comment]
> 还是去掉迷你导航条吧，新窗口模式虽然可以召之即来，但是不能挥之即去，只能点击右上角的X关闭
也有人觉得调出导航条切换栏目麻烦，考虑下次在AriaNG选项里加个开关供你们选择。

**Comment by alexhua** [comment]
341aa5fd214a66bd204682b64c983e2a1d10219c 再三权衡，为了尽量少地修改AriaNG，我们没有提供开关选项。只对迷你侧边栏做了优化调整，只要显示宽度小于990px就会自动开启迷你模式，只占用很少地空间，相信大部分人都能接受。

**Comment by CCCAUCHY** [comment]
> [341aa5f](https://github.com/alexhua/Aria2-for-chrome/commit/341aa5fd214a66bd204682b64c983e2a1d10219c) 再三权衡，为了尽量少地修改AriaNG，我们没有提供开关选项。只对迷你侧边栏做了优化调整，只要显示宽度小于990px就会自动开启迷你模式，只占用很少地空间，相信大部分人都能接受。

迷你侧边栏是原版AriaNG的设计吗？
