### ISSUE TITLE
[建议] 网站黑名单判断

### ISSUE THREAD

**Issue by ttttmr** [alexhua/Aria2-for-chrome#11]
这个黑名单没有说是指`当前访问网站`还是`点击链接网站`还是`最终下载网站`

从使用来看这个是`当前访问网站`，测试如下（我开启了拦截最终下载地址，不知道有没有关系）

1. 在a.com中点击a.com/down下载链接，而a.com/down会重定向到b.com

此时添加b.com到黑名单无效，添加a.com到黑名单后成功

2. 在c.com点击a.com/down链接

此时添加a.com和b.com到黑名单都无效

建议综合考虑，不论入口，当前or点击or多重跳转，只要遇到了黑名单就放过，此时在1和2例子中加入a.com或b.com都可以实现黑名单效果

如果太麻烦的话，可以考虑在开启拦截最终下载地址时，仅使用最终下载地址判断

**Comment by alexhua** [comment]
功课做得很足，感谢反馈。
这个问题我已经发现了，考虑到是少数情况，暂时没有修正。
 
对于普通用户来说黑名单的直觉就是当前访问的网站，但往往会有你说的例2的情况，目前是只拿资源的直接URL做判断，所以你说的例2这种情况黑名单会失效，多重跳转这种情况不受影响。代码应该向直觉靠拢，下个版本会修正。

**Comment by alexhua** [comment]
Done
5a0da3be063a656d303eac84864309073a89fdcb
