### ISSUE TITLE
AriaNg extension page is unable to connect to aria2

### ISSUE THREAD

**Issue by Puncia** [alexhua/Aria2-for-chrome#110]
**Describe the bug**
The extension page shows a connection error whenever opened and the downloads are not handled by the extension.

**To Reproduce**
1. Go to chrome web store, install the extension
2. Open the extension page (Extensions -> Aria2 for Chrome)
3. See mentioned error

**Expected behavior**
The connection is established. 

**Screenshots**
![image](https://user-images.githubusercontent.com/4633311/206192535-9c3e049a-b706-4c9f-83a2-46f6abf6ddab.png)
![image](https://user-images.githubusercontent.com/4633311/206192627-5c8f5073-b7d1-4c51-aed1-b943458f1fe4.png)

**Desktop (please complete the following information):**
 - OS: Windows 11 22621.900
 - Chrome 108.0.5359.95

**Comment by alexhua** [comment]
After reading your descriptions, I think maybe you did not configure the extension correctly.

If your are not familiar with aria2, please follow the instructions below:
- First, download aria2 utility. 
- Second, run it in the terminal (or cmd) with typing `aria2c --enable-rpc`. 
- Third, enable auto-capture on the extension options page. The extension will then take over the download leading you to a high-speed download experience.

[Aria2 Download Link](https://github.com/aria2/aria2/releases/latest)

**Comment by Puncia** [comment]
Sorry, I completely missed the instructions at the top of the page. Everything works fine now, thank you.
