### ISSUE TITLE
能整个按扩展名分类下载到不同文件夹的功能吗？

### ISSUE THREAD

**Issue by drunkenQCat** [alexhua/Aria2-for-chrome#111]
**Motivation**
从某些网站下载音乐的时候就会很怀念idm的那种分类文件夹的功能。

**Feature Description**
A clear and concise description of what this feature does.
* 拦截下载，并分析扩展名所属文件类型
* 针对不同类型，指定不同的下载文件夹

**Is the solution code ready**
No
**Willing to maintain the related code in the future**
No

**Additional context**
![image](https://user-images.githubusercontent.com/39608175/206355120-8ab2ccb3-252f-4c7d-9e72-39555c8543d5.png)

![image](https://user-images.githubusercontent.com/39608175/206355159-d5693352-dd93-40ee-8a70-c4101b2ee29b.png)

**Comment by alexhua** [comment]
参考#76
简单的说就是需要你添加多个连接条目，设置不同的保存目录和URL Pattern，扩展会根据Pattern匹配下载地址，下载到相应的目录。
