### ISSUE TITLE
根据拓展名自动拦截下载有时失效以及拓展名黑名单与白名单的解释

### ISSUE THREAD

**Issue by yudong2ao** [alexhua/Aria2-for-chrome#112]
1、希望拓展配置页面有拓展名黑名单和白名单的解释，现在的解释文字完全一样，第一次用不清楚白名单是要拦截的还是不需要拦截的
![image](https://user-images.githubusercontent.com/59545510/209892144-eef95356-fc9a-4da4-a691-01d54736356c.png)
后续使用的过程中发现拓展名白名单是要拦截的，黑名单是不要拦截的，且白名单的优先级高于黑名单，建议白名单的解释文字调整为“设置需要自动拦截下载的拓展名，每行一个拓展名，*代表所有，且优先级高于拓展名黑名单”，黑名单的解释文字调整为“设置不需要自动拦截下载的拓展名，每行一个拓展名，*代表所有，且优先级低于拓展名黑名单”；

2、使用过程中需要自动拦截“.torrent”文件，其他类型文件均不拦截，设置如下图：
![image](https://user-images.githubusercontent.com/59545510/209892591-493a8cdf-a4dd-4a1d-959b-eb7d67bbfaa7.png)
且开启下载拦截，能够按期望只拦截”.torrent“文件，但是正常使用一段时间后（未做任何修改）便不能自动拦截”.torrent“文件，麻烦看看是否能复测到这个bug，我已经出行2次这个bug了；

**Comment by yudong2ao** [comment]
第2个拦截“.torrent"失败的问题已经解决，是因为有的网站的种子下载按钮上没有绑定种子地址，是通过js跳转重定向的，所以根本识别不到种子地址，所以也就拦截不到了

**Comment by alexhua** [comment]
1. 挺好的建议，下个版本优化一下。
2. js重定向的应该也能拦，能否给几个拦不住的例子待我分析一下？
