### ISSUE TITLE
Failed to download files from Web Telegram

### ISSUE THREAD

**Issue by jerryc05** [alexhua/Aria2-for-chrome#113]
不确定是这个扩展的问题还是上游的问题，但是我用这个扩展下载网页版 TG 里的任何文件 https://web.telegram.org/k/ 的时候 `aria2c` 提示 `errorCode=3 ResourceNotFound` 之类的。

但是使用原生浏览器下载是没有问题的，所以我怀疑是这些下载链接被请求了一次（拿到了 URL 之后）不允许第二次请求（之类的？

**Comment by alexhua** [comment]
看了一下，Web Telegram里的资源貌似是Blob数据，只能通过浏览器下载。
