### ISSUE TITLE
深色主題異常

### ISSUE THREAD

**Issue by o1232000** [alexhua/Aria2-for-chrome#116]
<img width="514" alt="2023-01-27 08_01_20-CompatWindow" src="https://user-images.githubusercontent.com/61830894/214977322-1c05e154-c75c-402d-adb5-3554132c37bb.png">

如圖，說明文字框呈現黑底黑字
官方1.3.3版已修正，求跟進，謝謝

**Comment by alexhua** [comment]
OK

**Comment by Dragon1573** [comment]
@alexhua 

1. 请问包含此次修复的 Release 大概会在多久后发布呢？
2. 请问能否将包含此次修复的两个补丁 Commit ( fc985f0 和 8bcb02f ) 同样作用到 `edge` 分支下？

**********

当前以 Clone 了最新的 `master` 分支，以解压插件形式安装。问题已确认修复 ❤️

**Comment by alexhua** [comment]
@Dragon1573 :

1.  这个不确定，都不是什么大改进，会先攒一段时间。
2. 可以

**Comment by alexhua** [comment]
@Dragon1573 昨天推送了全新的2.0版本上来，在MV3分支，代码全部重写，增加了一些功能和细节改进。
Chrome和Edge版合二为一了，Edge分支以后可能不用了。欢迎试用新版，有问题还请及时反馈。
新版可能会在充分测试后才会上架商店，近期会先发布一个小的改进版。

**Comment by Dragon1573** [comment]
![image](https://user-images.githubusercontent.com/49941141/218997292-fb8ff744-ef55-4f48-869a-27f48b60a5ae.png)

已 Checkout 到 https://github.com/Dragon1573/Aria2-for-edge/commit/191b1e00a1bd13a491c3c0b5d796876904648914 进行安装，目前正在试用中。

**Comment by Dragon1573** [comment]
> 新版可能会在充分测试后才会上架商店，近期会先发布一个小的改进版。

卸载了 Git 解压版的 Aria2 for Edge 后，我尝试在 Edge 中直接下载 [`aria2e-v1.5.11.crx`](https://github.com/alexhua/Aria2-for-chrome/releases/download/v1.5.11/aria2e-v1.5.11.crx) 。Edge 总会在 `*.crx` 下载完成后自动执行安装过程，在安装过程完成后自动删除 `*.crx` 文件。

![image](https://user-images.githubusercontent.com/49941141/218999774-f18ee992-d27c-4dfc-bba1-2cafab5e7a8b.png)

![image](https://user-images.githubusercontent.com/49941141/219001000-afada6b2-5586-4d3f-af5d-31ac19ca89c6.png)

在检查 [alexhua/master - `.github/workflows/release.yml`](https://github.com/alexhua/Aria2-for-chrome/blob/master/.github/workflows/release.yml) 后，看到 [第23～27行](https://github.com/alexhua/Aria2-for-chrome/blob/master/.github/workflows/release.yml#L23-L27) 只使用了 [`vimtor/action-zip@v1`](https://github.com/vimtor/action-zip) 生成 `*.crx` 扩展包。

![image](https://user-images.githubusercontent.com/49941141/219006643-956e8c78-1d2e-4c5a-8e36-ebaa76b57b0c.png)

我查阅了 [此文档](https://crxdoczh.readthedocs.io/en/latest/3-reference/CRX.html) ，`*.crx` 是一个特殊的、带头特定格式文件头的 ZIP 压缩文件，而使用上面提到的 `vimtor/action-zip` 并不会添加相关文件头，造成 Edge 不识别。

GitHub Marketplace 中还提供了方便的 [`sign-chrome-extension-crx-file`](https://github.com/marketplace/actions/sign-chrome-extension-crx-file) ，是否可以考虑一下在后续暂不上线 Chrome Store 和 Edge Store 的预览发行版中对 `*.crx` 进行签名？

**Comment by alexhua** [comment]
> GitHub Marketplace 中还提供了方便的 [sign-chrome-extension-crx-file](https://github.com/marketplace/actions/sign-chrome-extension-crx-file) ，是否可以考虑一下在后续暂不上线 Chrome Store 和 Edge Store 的预览发行版中对 *.crx 进行签名？

@Dragon1573 挺好的建议，有空我改进一下。

有任何其他建议，欢迎去讨论区讨论 https://github.com/alexhua/Aria2-for-chrome/discussions/118
