### ISSUE TITLE
询问下多服务器的设置问题

### ISSUE THREAD

**Issue by KangMz** [alexhua/Aria2-for-chrome#119]
扩展设置中的 Aria2-RPC-Server 选项可以添加多个服务器，但似乎不能同步到 AriaNG中。而且如果在AriaNG设置好多个服务器，然后在扩展设置中点击保存，还会导致AriaNG中的设置被覆盖并且还不是正确的

想问下这个选项的操作逻辑是什么呢

**Comment by alexhua** [comment]
V1.x.x的版本点保存的时候，只能同步一个默认的Aria2-RPC-Server到AriaNG，会覆盖掉AriaNG那边的首选Aria2-RPC-Server。
V2.x.x版已经改进了，点保存会同步所有RPC设置过去，还会提示是否覆盖，目前正在测试中， 充分测试后会上架商店。
https://github.com/alexhua/Aria2-for-chrome/releases/tag/v2.0-beta 欢迎试用
