### ISSUE TITLE
[image-downloader] 批量下载图片并重命名时的冲突问题

### ISSUE THREAD

**Issue by mzhboy** [alexhua/Aria2-for-chrome#120]
**Describe the bug**
[image-downloader](https://chrome.google.com/webstore/detail/image-downloader/cnpniohnfphhjihaiiggeabnkjhpaldj) 扩展用来批量下载网页中的图片，并使用其重命名功能为图片添加序号。这时出现了冲突。

**To Reproduce**
 1. 使用 `image-downloader` 扩展下载图片
 2. 使用 `image-downloader`的重命名功能
 3. `Aria2 for Chrome` 未对该网页域名加入黑名单
 4. 重新加载 `Aria2 for Chrome` 问题消失，当然再次使用 `image-downloader`  下载问题再次产生

**Expected behavior**
Chrome 提示扩展出现错误

**Screenshots**

![Snipaste_2023-03-19_16-20-42](https://user-images.githubusercontent.com/5281193/226162663-5589aace-a6b3-46d2-90e7-6623ad39aed5.jpg)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome
 - Version 109

**Comment by alexhua** [comment]
这个只要`下载拦截`开着就没法避免。有冲突临时关掉`下载拦截`即可。

**Comment by alexhua** [comment]
duplicated with #114
