### ISSUE TITLE
可否考虑增加对文本，使用右键导出功能

### ISSUE THREAD

**Issue by Peter-XL** [alexhua/Aria2-for-chrome#14]
目前插件仅在右键点击链接时会出现导出菜单，但有部分情况的磁力链接及下载链接都不是以链接方式展现的，所以是否可以考虑增加一下功能。

- 文本右键菜单导出到aria2功能
- 以上功能的开关

**Comment by alexhua** [comment]
好的，后续版本考虑加入这个功能。

**Comment by alexhua** [comment]
Done
5a0da3be063a656d303eac84864309073a89fdcb
