### ISSUE TITLE
默认RPC服务器的选择

### ISSUE THREAD

**Issue by Peter-XL** [alexhua/Aria2-for-chrome#15]
目前首个RPC服务器是默认截获链接后的下载服务器，但我在家和在公司都分别架设了aria2，分别负责不同的下载任务。但目前切换的方式比较麻烦，能否在UI上可以更加高效的切换呢？甚至可以同时调用多个RPC服务器呢？

**Comment by alexhua** [comment]
打开“下载前询问详细设置”
在AriaNG中配置多个目标地址
任务拦截后在AriaNG左上角切换目标地址
都是已有的功能，多摸索摸索

**Comment by ZhangTianrong** [comment]
我觉得指的应该是快速切换默认RPC而不是手动选择RPC吧，就是往往连续多个下载都需要使用某个机器，按照现有的方法，那么就要在几次下载的时候都在AriaNG里手动切换服务器。如果何以在设置界面添加选择默认服务器的方法，那么就省事很多了。

**Comment by alexhua** [comment]
> 我觉得指的应该是快速切换默认RPC而不是手动选择RPC吧，就是往往连续多个下载都需要使用某个机器，按照现有的方法，那么就要在几次下载的时候都在AriaNG里手动切换服务器。而且图标展示的下载信息是插件默认的而不是AriaNG上选择的，如果何以在设置界面添加选择默认服务器的方法，那么就省事很多了。

翻历史问题是个好习惯，点赞。不过可能你没注意到多个RPC Server的时候可以设置URL pattern，会根据下载URL自动选Server，设成“*”可以用来切换扩展的默认RPC Server。善用Pattern和Download location还可以实现下载文件自动分类归档。

**Comment by ZhangTianrong** [comment]
了解了。话说为什么要做`*`到`.*`的转换啊，如果是为了支持wildcard的话，`.zip`不应该能match`gzip`吧。建议把这个写在readme里？（话说测试的时候还开着“下载前询问详细设置”以为设置无效……）
