### ISSUE TITLE
能否在启动时不修改Aria2设置

### ISSUE THREAD

**Issue by zhengqwe** [alexhua/Aria2-for-chrome#154]
我的Aria2设置是通过配置文件加载的，但我每次点击图标启动软件时设置都会被修改，之前的版本没有这个问题

**Comment by alexhua** [comment]
你没在Aria2设置页面改过配置，他就是你配置文件里的配置。改过了，就去常规设置最下面点`重置Aria2设置`。那个每次启动的提示，下一版会去掉。
