### ISSUE TITLE
无法连接到 aria2c，导出下载任务失败

### ISSUE THREAD

**Issue by hubeibei** [alexhua/Aria2-for-chrome#17]
![image](https://user-images.githubusercontent.com/9840974/67651506-56db8a00-f97c-11e9-9ee7-0466754071a5.png)

大佬，浏览器右键导出百度网盘的文件，提示无法连接到Aria2c ，使用其他插件导出下载任务可以成功，但是下载一直失败，请问这是怎么回事呢

**Comment by SealinRepo** [comment]
我也是这样, 但是我的Aria2是配好的
![image](https://user-images.githubusercontent.com/14067275/68644929-84662d00-0551-11ea-85f2-3d809134396e.png)

**Comment by amwihgu** [comment]
我也是这样，明明点开Aria是连接成功的。

**Comment by L245T** [comment]
我也这个问题，在NG里面显示的aria2连接成功，但是下载的时候就提示无法连接

**Comment by amwihgu** [comment]
大家好，我这里的问题基本上解决了，分享一下：
插件的选项里的连接不能只用IP+端口，需要用Token，即（不带括号）：
http://token:【你的密码】@【你的域名或IP】:6800/jsonrpc

**Comment by 1024191579** [comment]
> 大家好，我这里的问题基本上解决了，分享一下：
> 插件的选项里的连接不能只用IP+端口，需要用Token，即（不带括号）：
> [http://token:【你的密码】@【你的域名或IP】:6800/jsonrpc](http://token:%E3%80%90%E4%BD%A0%E7%9A%84%E5%AF%86%E7%A0%81%E3%80%91@%E3%80%90%E4%BD%A0%E7%9A%84%E5%9F%9F%E5%90%8D%E6%88%96IP%E3%80%91:6800/jsonrpc)

谢谢大佬 太强了 直接把选项里的第一个替换成这个完美解决！
