### ISSUE TITLE
右键导出到aria2 RPC功能不能用

### ISSUE THREAD

**Issue by SealinRepo** [alexhua/Aria2-for-chrome#19]
![image](https://user-images.githubusercontent.com/14067275/68645153-18d08f80-0552-11ea-80a0-73f87e52ff10.png)

测试链接:
在163镜像页面上随便找的一个文件链接, 也不能右键添加下载任务
http://mirrors.163.com/archlinux/iso/2019.11.01/

**Comment by zhmars** [comment]
https://github.com/alexhua/Aria2-for-chrome#usage
> 扩展和AriaNG分别需要配置RPC地址

**Comment by issenn** [comment]
前提是AriaNG和扩展配置项已配置完成。

手动复制有效链接到AriaNG和以前的操作一致。
扩展右键导出度盘直链链接至RPC，部分链接会导出失败，如果是rar/zip的话，文件名不能识别，部分下载成功，部分直接失败。

**Comment by PhyX-Meow** [comment]
我遇到了相同的问题，我使用Edge Chromium，可以连接rpc但是无法导出，在chrome上可以正常使用

**Comment by everyx** [comment]
使用 https://github.com/binux/yaaw 是可以的，但是用这个就不行了，不清楚为什么

**Comment by alexhua** [comment]
Duplicate of #17

**Comment by everyx** [comment]
我这里清楚所有设置，然后先按照 #17 的选项设置之后，再设置 AriaNG 里面的选项，就可以了，不知道是不是顺序有关

**Comment by alexhua** [comment]
> 

> 我这里清楚所有设置，然后先按照 #17 的选项设置之后，再设置 AriaNG 里面的选项，就可以了，不知道是不是顺序有关
没有关系，两个是独立的。可能还是之前没设置好。

**Comment by anjia0532** [comment]
![image](https://user-images.githubusercontent.com/15098916/88749882-db1aa200-d186-11ea-83d4-1d97e96e1035.png)

![image](https://user-images.githubusercontent.com/15098916/88749860-d0600d00-d186-11ea-9685-ee5b986347ac.png)
