### ISSUE TITLE
希望提供BT下载批量取消勾选文件的功能

### ISSUE THREAD

**Issue by Yuki-Nagato** [alexhua/Aria2-for-chrome#2]
有些BT种子中包含非常多的文件，而我只需要其中几个，如果一个个手动取消勾选的话很麻烦。

希望能提供一个全部取消选择的按钮，如果能有一个按文件类型选择的功能就更好了。

**Comment by ihipop** [comment]
你说的这个是AriaNG的功能 吧

**Comment by Yuki-Nagato** [comment]
![种子文件列表](https://user-images.githubusercontent.com/21074571/59493933-a41ff900-8ebe-11e9-85d6-85f5e0442291.png)

比如这种情况，我想批量取消选择，希望添加一个全部取消选择的按钮。

**Comment by ihipop** [comment]
这是 AriaNG 的界面 你去 AriaNG的 REPO提交FR https://github.com/mayswind/AriaNg
