### ISSUE TITLE
本插件与 Nimbus 截屏插件冲突？

### ISSUE THREAD

**Issue by ElfSundae** [alexhua/Aria2-for-chrome#22]
Aria2 for Chrome 1.2.9
![image](https://user-images.githubusercontent.com/526008/70627069-7db9fb00-1c60-11ea-98ff-1c8464de81f1.png)
Nimbus 截幕 & 屏幕录像机：https://chrome.google.com/webstore/detail/nimbus-screenshot-screen/bpconcjcammlapcogcnnelfmaeghhagj

Chrome 有时会报这个错。不知道怎么出来的，把两个插件来回重启测试均正常。

我是有一次下载文件时，Aria2 没拦截到，去 Chrome 插件设置界面一看，有这个错。
有这个错误时，两个插件貌似都能正常使用。

**Comment by ElfSundae** [comment]
![image](https://user-images.githubusercontent.com/526008/71630859-598a8200-2c40-11ea-8896-8280d6e321c5.png)

**Comment by alexhua** [comment]
Chrome的一个bug，两个扩展同时拦截下载文件会冲突，目前无解，如果影响使用只能临时关掉其中一个。

**Comment by ElfSundae** [comment]
OK
