### ISSUE TITLE
几个小建议

### ISSUE THREAD

**Issue by maxzhang666** [alexhua/Aria2-for-chrome#23]
不是很了解aria2的api

1、是否可以在导入链接的时候同时导入文件名，如识别的A标签则用A标签的名字作为文件名（做成开关最舒服）

2、是否可以在导入链接的同时设置代理，同样走配置中预先配置好的统一代理

3……我在想想

**Comment by alexhua** [comment]
1. A标签并不经常是文件名，所以不好处理
2. 不同用户需求不太一样，还是用户自己在Aria2c的配置文件里自定义比较合理，也可以选择下载前询问，然后在AriaNG新建页面手动设置。
感谢反馈。
