### ISSUE TITLE
请问一下是否有实现此功能的可能？

### ISSUE THREAD

**Issue by Azreulo** [alexhua/Aria2-for-chrome#24]
感谢你的插件，很棒~

抱歉我不是很懂Chrome的机制，想请教是否能实现这种可能，比如某个链接，正常点击不会拦截到Aira2，正常使用Chrome下载。但是当比如按住Alt点击的时候，拦截到Aira2下载。

另外一个是希望增加一个扩展名黑白名单的功能，比如Txt经常希望在浏览器中打开。

Thanks。

**Comment by alexhua** [comment]
这个不是很好实现，可以在 chrome://extensions/shortcuts 设置快捷键，即时控制自动拦截的开关。
