### ISSUE TITLE
[Feature] 能否拦截到下载的时候询问是否使用浏览器自带下载？

### ISSUE THREAD

**Issue by abcfy2** [alexhua/Aria2-for-chrome#35]
某些网站会对多线程下载封锁，导致没法使用，必须使用浏览器自带的下载才可以。另外大部分情况下我也不会时刻常开aria2，某些不需要使用Aria2下载的场景我就希望直接用浏览器自带的下载就好了，就懒得开aria2了

不知是否可以考虑在拦截到下载的时候弹出类似于Firefox下[Aria2 下载器集成组件](https://addons.mozilla.org/zh-CN/firefox/addon/aria2-integration/) 这个插件弹出的交互式对话框，就像这样:

![](https://addons.cdn.mozilla.net/user-media/previews/full/189/189863.png?modified=1543520905)

在这个交互式对话框界面上，用户可以选择使用浏览器自带的下载器完成下载，也可以选择发送到其他Aria2实例上，要不是这个插件不支持自定义JSON RPC服务器地址的别名，我简直就认为这个插件是我心目中最完美的Aria2插件了

**Comment by alexhua** [comment]
开了下载前询问，拦截后决定权就交给AriaNG了，目前不想对AriaNG做过多改动。既然用的情况比较少，可以考虑设置下合适的黑白名单。这个需求先记在这了。

**Comment by abcfy2** [comment]
不知道是否可以考虑拦截到的时候先不要着急交给AriaNG,而是弹出像截图那样的对话框，可以再次做某些调整呢？

**Comment by raining1123** [comment]
有同样需求

**Comment by wnbh** [comment]
同样需求

**Comment by alexhua** [comment]
这个问题现在基本解决了，打开`检测Aria2`状态，如果自动拦截时Aria2没有打开，扩展会自动再次调用Chrome进行任务下载，能自动化的尽量自动化不给用户增加选择负担。
某些文件临时不需要拦截的话，可以用顺手用`Alt+A`关掉自动拦截，也没有很麻烦。

**Comment by alexhua** [comment]
![image](https://github.com/alexhua/Aria2-Explorer/assets/1220458/0b07c671-e49f-4b10-ba85-146155aa6f5e)
