### ISSUE TITLE
Magnet url support

### ISSUE THREAD

**Issue by vipinaggar** [alexhua/Aria2-for-chrome#38]
Pls add support for magnet url like in the below mentioned extension
https://chrome.google.com/webstore/detail/aria2-manager/lbfekjdfefiipnbkpgldhicajcoldcmb

it make the addon complete and we do not have to install any app for magnet .

**Comment by alexhua** [comment]
It is not a decent method to inject JS to every page you visited to capture the uncommon magnet link.
Exporting it from context menu, you deserve it, dude.

**Comment by alexhua** [comment]
Dude, I've found the right way to support magnet URL, just wait for the next version.

**Comment by vipinaggar** [comment]
Thanks on desktop the option is working but in android kiwi browser the option gets automatically unticked on saving the option page

**Comment by alexhua** [comment]
I'm not sure what results in this problem, maybe android system or kiwi browser. Anyway it is out of my support range.

**Comment by vipinaggar** [comment]
So you dont provide support for android because it is not the fault of kiwi browser if all functions of your addon is working I suppose.

**Comment by login404** [comment]
这个是如何工作的?
选项里开启了拦截磁链跟下载拦截
但点击磁链的超链接并无反映

**Comment by alexhua** [comment]
> 这个是如何工作的?
> 选项里开启了拦截磁链跟下载拦截
> 但点击磁链的超链接并无反映

注册了系统Magnet协议的默认打卡程序
你是什么系统？
![批注 2020-08-12 184835](https://user-images.githubusercontent.com/1220458/90007081-a7826080-dccc-11ea-9b76-88e921d6109c.png)
开启拦截，点保存后，会弹出左上角的对话框，需要点允许。

**Comment by login404** [comment]
> > 这个是如何工作的？
> > 选项里开启了拦截磁链跟下载拦截
> > 但点击磁链的超链接无法反映
> 
> 注册了系统磁铁的协议默认打卡程序
> 你的英文什么系统- ？ 开启拦截，点保存后，会弹出左上角的对话框，需要点允许。
> ![批注2020-08-12 184835](https://user-images.githubusercontent.com/1220458/90007081-a7826080-dccc-11ea-9b76-88e921d6109c.png)
懂了 我全局把设置默认协议给禁了…
看描述说是网站以为扩展不会用到

**Comment by login404** [comment]
不支持隐身模式?
把其他所有扩展禁用后
仍显示遭到某个扩展程序的阻止

**Comment by alexhua** [comment]
> 不支持隐身模式?
> 把其他所有扩展禁用后
> 仍显示遭到某个扩展程序的阻止

对支持不了，隐身模式下拿不到用户设置。
