### ISSUE TITLE
Magnet url option not working in android

### ISSUE THREAD

**Issue by vipinaggar** [alexhua/Aria2-for-chrome#39]
![Screenshot_2020-06-13-11-27-51](https://user-images.githubusercontent.com/65840891/84565671-384dc600-ad88-11ea-9f56-83b2b5f07c6e.png)

**To Reproduce**
1. Go to 'options...'
2. Click on 'capture magnet url'
3. Scroll down to 'save and refresh'
4. See error capture manget url option gets unticked

**Desktop (please complete the following information):**
 - OS: android oreo
 - Browser kiwi browser yandex and ungoogled chromium
 - Version latest

**Comment by alexhua** [comment]
Obviously, your browser dose not support  registerProtocolHandler function.
