### ISSUE TITLE
拦截微云下载失败

### ISSUE THREAD

**Issue by ihipop** [alexhua/Aria2-for-chrome#4]
实测是没带Cookies去下载 我手动添加URL和Cookies后能正常下载
微云的下载域名和当前页面的域名不一致而且有跳转，最终拦截到了正确的下载地址，但是Cookies没带上

**Comment by alexhua** [comment]
好的，待我看看。

**Comment by abcfy2** [comment]
+1，同样遇到这个问题，而用firefox的`Aria2 下载器集成组件`插件没问题

**Comment by bulubula** [comment]
请问有办法了吗，为什么带了cookie还是不行啊，，难道还要带别的headers，，

**Comment by alexhua** [comment]
> 实测是没带Cookies去下载 我手动添加URL和Cookies后能正常下载
> 微云的下载域名和当前页面的域名不一致而且有跳转，最终拦截到了正确的下载地址，但是Cookies没带上

问题定位清楚了，确实没有带上Cookies，Aria2c配置不当也会导致下载失败比如使用了“use-head=true”
这几天会更新版本解决这个问题，感谢反馈
