### ISSUE TITLE
可以导出到服务器的jsonrpc下载吗

### ISSUE THREAD

**Issue by xyy55** [alexhua/Aria2-for-chrome#40]
**Motivation**
Description of why you want add new feature. Ex. I'm always frustrated when [...]

**Feature Description**
A clear and concise description of what this feature does.
* xxxxxx
* xxxxxx

**Is the solution code ready**
Yes / No

**Willing to maintain the related code in the future**
Yes / No

**Additional context**
Add any other context or screenshots to let common user know what this feature is.

**Comment by xyy55** [comment]
就是弹出的窗口还是localhost:6800

**Comment by alexhua** [comment]
完全看不出你的意图，照着Feature Request模版描述一下吧。

**Comment by Blankdlh** [comment]
同样的问题，RPC 地址设置无效，一直都是 localhost

**Comment by alexhua** [comment]
> 同样的问题，RPC 地址设置无效，一直都是 localhost

用的哪种下载方式，右键导出，下载前询问还是自动拦截下载？

**Comment by alexhua** [comment]
no response.
