### ISSUE TITLE
how to enable aria2 for Windows?

### ISSUE THREAD

**Issue by candrapersada** [alexhua/Aria2-for-chrome#41]
how to enable aria2c.exe for Windows? and how to download video from any website online?

**Comment by EltonChou** [comment]
Worng place to ask questions about aria2

https://aria2.github.io/

**Comment by alexhua** [comment]
> how to enable aria2c.exe for Windows? and how to download video from any website online?
1. Just download aria2c windows version and run it.
2. You should find an extension that could sniff the video URL and issue the download.
