### ISSUE TITLE
百度直链下载的问题

### ISSUE THREAD

**Issue by jzysl123** [alexhua/Aria2-for-chrome#42]
因为要下载百度网盘的直链
Aria2-RPC-Server端把ua改成LogStatistic才能下载

在解析好百度网盘的直链后 右键推送下载地址到Aria2失败
但是直接把下载地址粘贴到Aria2可以下载成功
不知道哪个环节出现问题。。。推送的时候是默认ua吗？

**Comment by alexhua** [comment]
对，直接导出或者自动拦截会带浏览器的UA，主要是为了模拟浏览器下载。
要模拟百度盘下载直链，可能需要你自己创建。
