### ISSUE TITLE
Download path for newly added files is wrong

### ISSUE THREAD

**Issue by ferrouswheel** [alexhua/Aria2-for-chrome#43]
Files added with this Chrome plugin have the wrong download path.

I have configured aria2 to use a specific directory: `/mnt/Media/incoming`

However, new files are added with `/Media/incoming` as the directory, and the download fails.

If I add the file manually using my webserver install of Aria2-ng, then it works fine. The same if I start a download using aria2c from the CLI.

The plugin used to work fine. So I think there may be a cache problem?

**Comment by ferrouswheel** [comment]
I looked in the chrome extension options and there was a separate field for the download directory that was incorrect. I don't remember changing this at all, but it works now.

**Comment by alexhua** [comment]
> I looked in the chrome extension options and there was a separate field for the download directory that was incorrect. I don't remember changing this at all, but it works now.

Yes, be careful to set your download path since there is no path verification right now.
