### ISSUE TITLE
 添加及监视服务端时的错误。

### ISSUE THREAD

**Issue by wy16W2pIilK1xgqN** [alexhua/Aria2-for-chrome#45]
Aria2-RPC-Server 选项 向 AriaNG 添加服务端设置时 默认会忽略后面的“jsonrpc”导致设置错误。

明明能正常使用服务但 监视服务端功能永远都显示为红色字母E，
`failed to connect  with aria2`

**Comment by alexhua** [comment]
没太明白你的意思，最好把你的RPC设置贴上来看看。

**Comment by wy16W2pIilK1xgqN** [comment]
![Snipaste_2020-08-24_20-30-55](https://user-images.githubusercontent.com/10376283/91046720-8403d200-e64b-11ea-9f5c-9325de8f13d7.png)
就是在 Aria2-RPC-Server 中设定了，ws://192.168.2.11:16800/jsonrpc ，
在 AriaNG  中只有 ws://192.168.2.11:16800/ ，没后面的 jsonrpc

**Comment by alexhua** [comment]
明白了， 扩展和AriaNG的RPC设置是分开的，只是为了方便，默认RPC有更改会自动导到AriaNG那边。
扩展这边不支持WS协议，你要用WS协议，可以先在扩展选项这边改成HTTP，再去AriaNG那边改成WS，这样两边就都可以用了。

**Comment by wy16W2pIilK1xgqN** [comment]
我明白了，谢谢回复！
建议在扩展介绍中注明。

**Comment by alexhua** [comment]
> 我明白了，谢谢回复！
> 建议在扩展介绍中注明。

有时候写得越多，小白用户越迷，越不敢用，甚至有些人根本不看。
我在代码里做下处理吧，也感谢你的反馈。
