### ISSUE TITLE
一直提示无法链接aria2，导出任务失败

### ISSUE THREAD

**Issue by qianmianyao** [alexhua/Aria2-for-chrome#46]
但是我确实是启用了aria2，前端也显示已链接

**Comment by alexhua** [comment]
信息提供的详细一点，别人可能更愿意帮你解答。

RPC 设置贴上来

**Comment by qianmianyao** [comment]
## aria2c --conf-path=./aria2.conf ##
#允许rpc
enable-rpc=true
#允许非外部访问
rpc-listen-all=true
#RPC端口, 仅当默认端口被占用时修改
rpc-listen-port=6800

#最大同时下载数(任务数), 路由建议值: 3
max-concurrent-downloads=32
#断点续传
continue=true
#同服务器连接数
max-connection-per-server=16
#最小文件分片大小, 下载线程数上限取决于能分出多少片, 对于小文件重要
min-split-size=10M
#单文件最大线程数, 路由建议值: 5
split=256
#下载速度限制
max-overall-download-limit=0
#单文件速度限制
max-download-limit=0
#上传速度限制
max-overall-upload-limit=0
#单文件速度限制
max-upload-limit=0

#文件保存路径, 默认为当前启动位置
dir="./"
#使用代理
all-proxy=localhost:1080
#添加引用页
referer=http://images.dmzj.com/
# 设置的RPC授权令牌, v1.18.4新增功能 , 取代 --rpc-user 和 --rpc-passwd 选项
rpc-secret=123456

**Comment by qianmianyao** [comment]
> ## aria2c --conf-path=./aria2.conf
> #允许rpc
> enable-rpc=true
> #允许非外部访问
> rpc-listen-all=true
> #RPC端口, 仅当默认端口被占用时修改
> rpc-listen-port=6800
> 
> #最大同时下载数(任务数), 路由建议值: 3
> max-concurrent-downloads=32
> #断点续传
> continue=true
> #同服务器连接数
> max-connection-per-server=16
> #最小文件分片大小, 下载线程数上限取决于能分出多少片, 对于小文件重要
> min-split-size=10M
> #单文件最大线程数, 路由建议值: 5
> split=256
> #下载速度限制
> max-overall-download-limit=0
> #单文件速度限制
> max-download-limit=0
> #上传速度限制
> max-overall-upload-limit=0
> #单文件速度限制
> max-upload-limit=0
> 
> #文件保存路径, 默认为当前启动位置
> dir="./"
> #使用代理
> all-proxy=localhost:1080
> #添加引用页
> referer=http://images.dmzj.com/
> rpc-secret=123456

**Comment by qianmianyao** [comment]
#允许rpc
enable-rpc=true
#允许非外部访问
rpc-listen-all=true
#RPC端口, 仅当默认端口被占用时修改
rpc-listen-port=6800

#最大同时下载数(任务数), 路由建议值: 3
max-concurrent-downloads=32
#断点续传
continue=true
#同服务器连接数
max-connection-per-server=16
#最小文件分片大小, 下载线程数上限取决于能分出多少片, 对于小文件重要
min-split-size=10M
#单文件最大线程数, 路由建议值: 5
split=256
#下载速度限制
max-overall-download-limit=0
#单文件速度限制
max-download-limit=0
#上传速度限制
max-overall-upload-limit=0
#单文件速度限制
max-upload-limit=0

#文件保存路径, 默认为当前启动位置
dir="./"
#使用代理
all-proxy=localhost:1080
#添加引用页
referer=http://images.dmzj.com/
rpc-secret=123456

**Comment by alexhua** [comment]
chrome-extension://mpkodccbngfoacfalldjimigbofkhgjn/options.html
不是Aria2的配置，是扩展的设置，上面这个地址。

**Comment by alexhua** [comment]
长时间没有回复先关了，建议检查下扩展选项设置，八成是RPC地址没有设置好。

**Comment by alexhua** [comment]
还有一种可能，你可能修改了扩展的“可读取和更改网站数据”这个设置。
