### ISSUE TITLE
请问拦截开关切换快捷键的问题

### ISSUE THREAD

**Issue by stevennight** [alexhua/Aria2-for-chrome#5]
请问一下这个是哪里设置呀？ 看了一下代码，似乎默认是alt+A，但是我这边似乎不能生效。谢谢。

**Comment by alexhua** [comment]
> 请问一下这个是哪里设置呀？ 看了一下代码，似乎默认是alt+A，但是我这边似乎不能生效。谢谢。
Chrome用得不精啊兄弟
Chrome里统一设置 chrome://extensions/shortcuts
