### ISSUE TITLE
[Feature Request] 仅在Aria2开启时拦截浏览器下载

### ISSUE THREAD

**Issue by ZZYSonny** [alexhua/Aria2-for-chrome#51]
**Motivation**
平时因为只用aria2下一些比较慢的大文件，我没有给aria2c设置开机自启。没开aria2的时，浏览器的下载被拦截，这个下载就直接不会出现了。

**Feature Description**
在下载时检测Aria2连接状态，如果无法连接则不拦截下载，并且弹出通知。

**Is the solution code ready**
No

**Comment by alexhua** [comment]
建议不错，考虑下个版本加入，不过可能需要你同时开启监测Aria2状态。
