### ISSUE TITLE
Ask detail settings before export to ARIA2 RPC

### ISSUE THREAD

**Issue by candrapersada** [alexhua/Aria2-for-chrome#54]
How to Ask detail settings before export to ARIA2 RPC?
![aaaa](https://user-images.githubusercontent.com/36833664/104673715-db96fd00-5714-11eb-8fa9-00d7601e7ab4.PNG)

**Comment by alexhua** [comment]
If you select the "ask details settings before download" option, it will only ask detail settings before auto-capture is triggered at present.

**Comment by candrapersada** [comment]
how to enable "ask details settings before download" to click the right button
![image](https://user-images.githubusercontent.com/36833664/105277658-6a54bf80-5bd6-11eb-92ea-ea284ad90bb7.png)

**Comment by alexhua** [comment]
You can copy the link to ariaNG to new a task manually and then tune the option as you need.

**Comment by candrapersada** [comment]
"ask details settings before download"
![Capture](https://user-images.githubusercontent.com/36833664/105621611-08958f00-5e3c-11eb-8f51-bebb340e3f53.PNG)
