### ISSUE TITLE
擴充功能設定頁面 Aria2-RPC-Server 密碼含特殊字元時設定失敗

### ISSUE THREAD

**Issue by johnnyslee** [alexhua/Aria2-for-chrome#55]
**Describe the bug**
如題；
#17 要用那個 work-around 的根本原因很可能就是密碼剖析失敗。

**To Reproduce**
1. 把 Aria2 的 rpc-secret 設為包含 # 字元的字串
2. 在擴充功能設定頁面 Aria2-RPC-Server 正常的在各欄輸入（不使用 #17 的 work-around）
3. 按下面的 Save 按鈕
4. 打開 Chrome 的 console 會顯示 Stored Rpc Url is invalid! RpcUrl options.js:336
5. 再設定 Aria2 把 rpc-secret 包含的 # 字元改為 ^
6. 重複 2 和 3
7. 成功加入 server：AriaNG 端能取得 server 設定

**Expected behavior**
rpc-secret 設為 Aria2 本身容許的任何密碼，在擴充功能設定頁面中也能正常設定。

**Screenshots**
N/A

**Desktop:**
 - OS: Ubuntu 20.04.1
 - Browser: Google Chrome
 - Version: 87.0.4280.141 (正式版本) (64 位元)

**Additional context**
N/A

**Comment by alexhua** [comment]
感谢反馈，问题确实存在。
