### ISSUE TITLE
建议增加“下载路径”的重写功能

### ISSUE THREAD

**Issue by RyoLee** [alexhua/Aria2-for-chrome#56]
**Motivation**
“下载路径”增加了file://的超链接如果是本机上运行的aria2很好用，但是如果是nas或者其他远程设备上就无法使用了

**Feature Description**
A clear and concise description of what this feature does.
* 增加一个是否重写的开关和规则输入框，允许以关键词或正则等形式替换超链接，实现 file://downloads  -> http://192.168.*.*/files/Download

**Is the solution code ready**
No

**Willing to maintain the related code in the future**
No

**Additional context**
Add any other context or screenshots to let common user know what this feature is.

**Comment by alexhua** [comment]
没明白你的使用场景，为什么要用超链，下载路径是一个远程地址，aria2支持远程地址吗？

**Comment by RyoLee** [comment]
类似**远程下载取回**这个操作
对于aria2部署在NAS或者非本机的其他设备上的情况，所有的下载都是“远程下载”，目前这个地方跳转路径是"远端的本地路径"[file://downloads]（比如docker部署的话是容器内的一个路径），这个跳转对本地端是没有用的，点击之后只会是一个ERR_FILE_NOT_FOUND页面，因为本地是一台windows环境根本就没有“/downloads”这个文件夹，相比linux下还能自己创建一个一样的/downloads文件夹然后挂载nfs上去
这里操作就有点僵硬了，每次下载完手动win+e再进挂载的网络存储路径一级一级到下载的这个对应的文件夹，或者点击pin在快速访问的文件夹，也有点别扭
如果可以编写规则自定义，比如我把[file://downloads]改写成[file://192.168.10.10/docker/aria2/temp]，那么在下载完成后直接点击这里的超链接就可以弹出资源管理器并且到达本地和远端对应的位置，类似的也可以是一个远端的http目录服务比如[http://192.168.10.10/webdir/]
其实如果可以的话自己用油猴直接替换就OK了，不过插件好像不能作用于插件页面就很难受

**Comment by alexhua** [comment]
明白你的意思了，搞了半天你说的是AriaNG里任务详情的那个“下载路径”。换成远程地址简单，判断aria2不在本地运行，前缀就换成你aria2所在的服务器地址就行。问题是访问远程的目录用什么协议呢，这个不好确定。就改写成[file://192.168.10.10/docker/aria2/temp]或者[(ftp|http)://192.168.10.10/docker/aria2/temp]不能保证完全正常工作，这个需求有点小众不能做成通用功能。
