### ISSUE TITLE
拓展无法连接而AriaNG可以

### ISSUE THREAD

**Issue by UmbraNix** [alexhua/Aria2-for-chrome#57]
http协议连接本地的Aria2，启用了授权令牌，设置好以后内置的AriaNG可以正常连接，但是拓展连接不上，显示“Failed to connect with Aria2, Reason: Unauthorized., E"
在AriaNG里可以通过手动输入链接正常下载，但是没法拦截下载链接还是挺麻烦的，现在很多下载链接都通过跳转隐藏起来了qwq
目前通过取消授权令牌可以使用，但我觉得这是程序的一个bug，还是有必要告知一下

**Comment by alexhua** [comment]
secretkey里有特殊字符吗，比如 "# / ? "

**Comment by alexhua** [comment]
Duplicate with #55
