### ISSUE TITLE
【下载前手动设置各种详细参数】这个功能是否可以在右键菜单中也生效&自定义下载页面可否在新tab打开

### ISSUE THREAD

**Issue by nukewarrior** [alexhua/Aria2-for-chrome#58]
举例，网页上有一段磁链，我选中后右键选择导出到XXX，这时候插件默认使用的是aria2的默认地址，可否让插件也进入自定义设置下载的页面呢。
同时，可否将自定义下载页面可否在新tab打开呢，谢谢

**Comment by alexhua** [comment]
导出的时候，所有的RPC地址都会作为选项列出来，aria2地址是用户自己选的呦。
导出这个功能的目的就是快速导出，改了可能会影响其他用户的使用习惯，想要详细设置可以使用自动拦截功能，而且已经支持拦截磁链了。
这里做个小调查，导出的时候一般会进行哪些参数设置呢？

**Comment by nukewarrior** [comment]
> 导出的时候，所有的RPC地址都会作为选项列出来，aria2地址是用户自己选的呦。
> 导出这个功能的目的就是快速导出，改了可能会影响其他用户的使用习惯，想要详细设置可以使用自动拦截功能，而且已经支持拦截磁链了。
> 这里做个小调查，导出的时候一般会进行哪些参数设置呢？

主要是选择目的地文件夹，通常来说会直接下载到/downloads文件夹，但是有些文件，为了方便管理，会选择下载到其他文件夹，譬如/downloads/hentai  :P

**Comment by alexhua** [comment]
> > 导出的时候，所有的RPC地址都会作为选项列出来，aria2地址是用户自己选的呦。
> > 导出这个功能的目的就是快速导出，改了可能会影响其他用户的使用习惯，想要详细设置可以使用自动拦截功能，而且已经支持拦截磁链了。
> > 这里做个小调查，导出的时候一般会进行哪些参数设置呢？
> 
> 主要是选择目的地文件夹，通常来说会直接下载到/downloads文件夹，但是有些文件，为了方便管理，会选择下载到其他文件夹，譬如/downloads/hentai :P

同一个aria2 Server你可以多创建几个条目然后设置不同的download location，导出的时候就可以选择下载目录了。
