### ISSUE TITLE
Request heades are not captured from download request

### ISSUE THREAD

**Issue by geekscrapy** [alexhua/Aria2-for-chrome#61]
In reference to this ticket: https://github.com/mayswind/AriaNg/issues/566

If I try and download a file which needs authentication the extension does not capture the request headers, and therefore cannot access authenticated resources.

If you manually add the headers it works.

**Comment by alexhua** [comment]
As you described in mayswind/AriaNg#566, it work as design. when you create task manually in the AriaNG, extension will not capture cookies from chrome.

**Comment by geekscrapy** [comment]
> As you described in [mayswind/AriaNg#566](https://github.com/mayswind/AriaNg/issues/566), it work as design. when you create task manually in the AriaNG, extension will not capture cookies from chrome.

I'm talking about the capture download function which is automatic. I would expect it to capture the headers? Otherwise I may aswell just copy and put the URL in aria2c directly.

**Comment by geekscrapy** [comment]
This is the same issue as #44

**Comment by alexhua** [comment]
As design，the extension will pass cookies and referer to aria2. About your case, would you please tell me how to re-produce？

**Comment by alexhua** [comment]
Duplicate with #44
