### ISSUE TITLE
Monitoring aria2 status leads to high CPU usage

### ISSUE THREAD

**Issue by diyijing** [alexhua/Aria2-for-chrome#63]
**Describe the bug**
查看日志发现一直在处理 chrome 的请求
header中 `Origin: chrome-extension://mpkodccbngfoacfalldjimigbofkhgjn` 判断来自该扩展，实测取消勾选后cpu占用恢复正常
```
aria2c --log - --enable-rpc --rpc-secret xxxxx 
```

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/18437933/108365382-1e775380-7232-11eb-9838-6bb5e3ed749a.png)
![image](https://user-images.githubusercontent.com/18437933/108365575-54b4d300-7232-11eb-8bb2-e42d7dbb30f9.png)

**Desktop (please complete the following information):**
 - OS: OS X
 - Browser: chrome
 - Version: latest

**Comment by alexhua** [comment]
在Windows平台试了一下，密码设置不正确时aria2的CPU占用确实会升高，10%左右，Mac上42%确实偏高。
监测aria2状态本身没有多少操作，只是一个简单的网络请求，应该是Aria2本身的问题。

两点建议：
1. 在选项页把密码改对了
2. 给aria2c项目提issue

**Comment by alexhua** [comment]
好了，这个坑算是填上了。
