### ISSUE TITLE
在Vivaldi上无法工作

### ISSUE THREAD

**Issue by lanshanguiyao** [alexhua/Aria2-for-chrome#64]
在Vivaldi浏览器安装后，安装完扩展无法工作（任何点击均无反馈），目前无法判断是Vivaldi的问题还是扩展的问题

**Desktop (please complete the following information):**
 - OS: Windows10 20H2
 - Browser Vivaldi | 3.6.2165.40
 - Version 1.5.2

**Comment by alexhua** [comment]
目前不对第三方套壳浏览器做技术支持，欢迎回到Chrome的怀抱。

不过给两点建议你可以试一下：
1. 进扩展选项页面Reset试试
2. 重装

**Comment by Gokou-Ruri** [comment]
> 目前除了Chrome和Edge，不对第三方套壳浏览器做技术支持。

您好，原版的Edge太过流氓了，Chrome则是自带功能太残缺，希望您能考虑适配vivaldi。

**Comment by alexhua** [comment]
> 您好，原版的Edge太过流氓了，Chrome则是自带功能太残缺，希望您能考虑适配vivaldi。

第三方套壳浏览器出现Bug：要么扩展本身出了Bug，要么第三方魔改出了Bug。如果确认是扩展的问题你可以提issue给扩展，如果是第三方的问题你可以提issue给第三方。
