### ISSUE TITLE
能否去除已连接提示

### ISSUE THREAD

**Issue by lopee** [alexhua/Aria2-for-chrome#65]
建议：
       一, 点击扩展图标弹出 标签页 或 小窗口 时，右上角总是提示“ARIA2 RPC 已连接”，其实左侧边栏 “ARIA2状态”就已经有显示是否连接正常，开启 监控aria2状态时，图标也能看到 ARIA2 RPC是否连接。所以，这个提示能否去掉？
       二, 选择弹出 小窗口时，左侧边栏能否默认留下几个小图标，方便查看正在下载，已下载等。目前下载完成后，要先点击“切换导航”才能查看已下载。
     例如这个扩展（已停止更新）没有已接连提示，弹出小窗口左侧也默认有小图标
https://github.com/jae-jae/Camtd

强迫症有点严重，见谅！

**Comment by alexhua** [comment]
两点意见提得都不错，那个边栏的显示策略确实很别扭。不过都是上游项目AriaNG的问题。
我这边改得越多每次升级AriaNG就越困难。
建议你提给 https://github.com/mayswind/AriaNg/issues/
