### ISSUE TITLE
ungoogled-chromium的兼容性问题

### ISSUE THREAD

**Issue by login404** [alexhua/Aria2-for-chrome#66]
**Describe the bug**
内置AriaNg在ungoogled-chromium上
打开后任何操作都无反应
右键导出 拦截 监测正常
AriaNg官方演示版可以正常工作
http://ariang.mayswind.net/latest

**To Reproduce**
1. 设置界面正确填写RPC配置
2. 点击扩展图标打开内置AriaNg
3. 右上角弹不出任何提示且点击左侧面板所有项目皆无反应

**Expected behavior**
内置AriaNg的正常工作

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows7 x64
 - Browser Chromium
 - Version 88.0.4324.190

**Additional context**
使用的浏览器具体程序文件
https://github.com/macchrome/winchrome/releases/download/v88.0.4324.190-r2202-Win64/ungoogled-chromium-88.0.4324.190-2_Win64.7z

**Comment by alexhua** [comment]
扩展选项页面Reset一下设置试试

**Comment by login404** [comment]
仍然不行
把浏览器数据文件夹清空
重新安装扩展后还是一样
