### ISSUE TITLE
本地AriaNG 操作无反应 无数据

### ISSUE THREAD

**Issue by Borber** [alexhua/Aria2-for-chrome#67]
**Describe the bug**
本地AriaNG 操作无反应 无数据
![image](https://user-images.githubusercontent.com/30563826/111034880-94966100-8452-11eb-9ef8-e848fef12152.png)

**Desktop (please complete the following information):**
 - OS: Archlinux
 - Browser Chrome 版本 89.0.4389.82（正式版本） （64 位）
 - Version V1.5.2

**Additional context**

**Comment by Borber** [comment]
我尝试过在线的 AriaNG 均可正常使用

**Comment by alexhua** [comment]
扩展选项页面Reset一下试试
