### ISSUE TITLE
Edge 89.0.774.50下AriaNG无法打开二级菜单

### ISSUE THREAD

**Issue by zcy85611** [alexhua/Aria2-for-chrome#68]
OS：Win10 20 H2 19042.804
Edge版本： 89.0.774.50

在最新版的Edge下，可以打开AriaNG的界面，但无法做出任何操作，点到任何一个二级选项里都无法显示内容

**Comment by alexhua** [comment]
Duplicate of #66

**Comment by alexhua** [comment]
最近报这个问题的人挺多。做个小调查，你的问题是升级后有的，还是全新安装有的？

**Comment by zcy85611** [comment]
全新安装

**Comment by Kuri-su** [comment]
删除重新安装后似乎正常

**Comment by Kuri-su** [comment]
> 删除重新安装后似乎正常

背景是 升级 Chrome 89 后, AriaNG 无法打开 二级菜单, 一直js 报错, 随后删除 AriaNG 扩展, 并在 Chrome Store 下载重装后 正常

**Comment by alexhua** [comment]
> > 删除重新安装后似乎正常
> 
> 背景是 升级 Chrome 89 后, AriaNG 无法打开 二级菜单, 一直js 报错, 随后删除 AriaNG 扩展, 并在 Chrome Store 下载重装后 正常

这个Bug很有意思，可以确定是AriaNG的问题，不过不是100%复现，还在分析中

**Comment by alexhua** [comment]
定位清楚了，有问题的朋友按一下步骤解决：
1. 选项页面Reset
2. 打开一次AriaNG

之后就可以正常使用了

下个版本会修复这个问题。
