### ISSUE TITLE
aria2的websocket模式,右键导出显示认证失败无法导入下载

### ISSUE THREAD

**Issue by kylinshine** [alexhua/Aria2-for-chrome#69]
#### 扩展中的配置
![1616769185(1)](https://user-images.githubusercontent.com/12790508/112649204-2e173700-8e85-11eb-9390-4d98cfb5366b.png)
#### ariaNG中改配置
![1616769006(1)](https://user-images.githubusercontent.com/12790508/112649980-e93fd000-8e85-11eb-8b2e-ad5217f69426.png)
#### 导出任务
![1616770665(1)](https://user-images.githubusercontent.com/12790508/112650821-c104a100-8e86-11eb-946c-af199595ab37.png)
#### 导出任务失败
![1616770297(1)](https://user-images.githubusercontent.com/12790508/112649999-ef35b100-8e85-11eb-8d2d-3cb13d26cc9b.png)
#### 直接添加ws协议认证的ariaNG任务
![1616770801(1)](https://user-images.githubusercontent.com/12790508/112651128-0e810e00-8e87-11eb-8d86-fcb8da463158.png)
#### ws协议认证的ariaNG任务下载完成
![1616770881(1)](https://user-images.githubusercontent.com/12790508/112651355-4720e780-8e87-11eb-9d15-13a233450b27.png)

**Comment by alexhua** [comment]
右键导出和自动下载目前还不支持WS协议，你可以打开“下载前询问详细设置”通过AriaNG导出任务。

**Comment by kylinshine** [comment]
#### 非常感谢您的回答！

**Comment by alexhua** [comment]
d7029d7fea362839001df0c92f99f9c821cc2b80
