### ISSUE TITLE
【建议】打开方式可以新增一个类似【SMMS图床】的独立弹窗

### ISSUE THREAD

**Issue by Noah1995** [alexhua/Aria2-for-chrome#7]
1丶增加下载的时候拓展小图标显示目前几个进程数值...

2丶就是拓展图标建议可以自定义设置...

3丶还有就是打开方式可以新增一个类似[【SMMS图床】](https://chrome.google.com/webstore/detail/smms%E5%9B%BE%E5%BA%8A/jfnojkljiahflcnlodkicgfbofclmdoi)的独立弹窗

**Comment by alexhua** [comment]
1. 这个需要后台持续刷新，后期会谨慎考虑加入
2. 这个貌似实现不了
3. 不错的建议，后续会权衡考虑
