### ISSUE TITLE
无法通过motrix进行下载

### ISSUE THREAD

**Issue by youlvlv** [alexhua/Aria2-for-chrome#70]
**Describe the bug**
所有下载链接均100%会出现，插件可以正常的找到下载器，且可以添加任务，但是无法下载，motrix提示错误#18

**Desktop (please complete the following information):**
 - OS: macos 11.2.3 (20D91)
 - Browser edge 89.0.774.63 
 - Version 1.5.3

**Comment by angussleeping** [comment]
我也遇到类似问题了，edge浏览器，1.5.3版本，右键发送就无法创建，nas端ariang提示错误18（failed to make the directory  cause：permission denied）错误描述是无法创建指定目录，但是复制链接到插件里，就没问题

**Comment by alexhua** [comment]
> 我也遇到类似问题了，edge浏览器，1.5.3版本，右键发送就无法创建，nas端ariang提示错误18（failed to make the directory cause：permission denied）错误描述是无法创建指定目录，但是复制链接到插件里，就没问题

RPC配置的Download Location里填错东西了？

**Comment by alexhua** [comment]
> 我也遇到类似问题了，edge浏览器，1.5.3版本，右键发送就无法创建，nas端ariang提示错误18（failed to make the directory cause：permission denied）错误描述是无法创建指定目录，但是复制链接到插件里，就没问题

RPC配置的Download Location里填错东西了？

**Comment by alexhua** [comment]
Duplicate of #75

**Comment by alexhua** [comment]
no response
