### ISSUE TITLE
kiwi浏览器上用不了

### ISSUE THREAD

**Issue by yyy33** [alexhua/Aria2-for-chrome#71]
作者你好，我使用的是最新版的kiwi浏览器，但是安装后提示“背景页，无效”
![image](https://user-images.githubusercontent.com/51548147/114980337-e6516180-9ebe-11eb-9070-28e470acac6c.png)
![image](https://user-images.githubusercontent.com/51548147/114980345-e94c5200-9ebe-11eb-9e63-8cee4cc629a7.png)

**Comment by alexhua** [comment]
kiwi目前不考虑支持和维护，能不能运行看运气。

**Comment by wxg1015** [comment]
可以用yandex  支持一级的选单  配置多个服务器时二级选单不可用         可以考虑使用 导出前询问详细参数来指定路径
