### ISSUE TITLE
【下载拦截】无法切换RPC地址，希望可以加上

### ISSUE THREAD

**Issue by link2fun** [alexhua/Aria2-for-chrome#72]
环境：
我配置的有多个RPC地址
![image](https://user-images.githubusercontent.com/19241982/116368200-ab461b00-a83a-11eb-83be-38878baa78ae.png)

使用的功能：
拦截下载

想达到的情景：
可以手动切换使用不同的RPC地址

现状：
目前发现好像默认使用的第一个，无法切换

期望:
希望可以加上修改（选择） 拦截下载 使用的RPC地址

**Comment by alexhua** [comment]
![image](https://user-images.githubusercontent.com/1220458/130550015-98bf32cc-918c-4353-9b33-53f5c4da53ff.png)
RPC地址默认第一个，想换哪个，哪个地址最后一天填上 “ * ”
