### ISSUE TITLE
勾选检测aria2状态后,在无下载任务的时候,不显示0图标.

### ISSUE THREAD

**Issue by yeezylife** [alexhua/Aria2-for-chrome#73]
没下载的时候图标上还亮着一个数字有点分心..是否可以考虑勾选检测aria2状态后,在无下载任务的时候,不显示0图标呢

**Comment by alexhua** [comment]
不显示怎么知道aria2是连通状态呢？年轻人这么容易被打扰，推荐你练习一下冥想。

**Comment by sherlocknieh** [comment]
> 不显示怎么知道aria2是连通状态呢？年轻人这么容易被打扰，推荐你练习一下冥想，提高一下专注力。

好家伙，看来不止我一个人有类似的困扰。可惜高高在上的作者就是听不进去呢。
你的Aria2这么脆弱吗？需要时时刻刻看着有没有断联？

@alexhua

**Comment by alexhua** [comment]
> 

哇，好可怜。。
