### ISSUE TITLE
希望能加入下载完成通知

### ISSUE THREAD

**Issue by wdboss** [alexhua/Aria2-for-chrome#74]
如同[Camtd](https://github.com/jae-jae/camtd)的下载完成通知功能

**Comment by info-CH** [comment]
图标上不是有数字吗？下载完成不就变成0 了

**Comment by wdboss** [comment]
> 图标上不是有数字吗？下载完成不就变成0 了

不显眼啊，而且数字归零之后不知道是下载完成了还是下载失败了。
最想要的功能还是点击下载完成的通知横幅直接打开finder并跳转到下载目录。

**Comment by alexhua** [comment]
> 如同[Camtd](https://github.com/jae-jae/camtd)的下载完成通知功能
![image](https://user-images.githubusercontent.com/1220458/130549359-210e456a-149a-4553-8940-8723fbfde0f0.png)
