### ISSUE TITLE
大佬，我在使用插件的时候有个问题，右键发送磁力链任务时，aria2提示错误，无法创建任务

### ISSUE THREAD

**Issue by angussleeping** [alexhua/Aria2-for-chrome#75]
使用的插件时1.5.3版本
edge浏览器，群晖docker的P3TERX的aria2和aria2ng，右键发送磁力链任务提示：发生错误（18），无法创建指定目录，是我设置的问题吗？
<img width="318" alt="Snipaste_2021-07-12_13-56-23" src="https://user-images.githubusercontent.com/34022591/125246484-6eab9b00-e324-11eb-9827-e0973eb11016.png">

**Comment by oklong** [comment]
应该是你设置问题吧，我用chrome，也是P3TERX的aria2，没有问题

**Comment by alexhua** [comment]
> 使用的插件时1.5.3版本
> edge浏览器，群晖docker的P3TERX的aria2和aria2ng，右键发送磁力链任务提示：发生错误（18），无法创建指定目录，是我设置的问题吗？
> <img alt="Snipaste_2021-07-12_13-56-23" width="318" src="https://user-images.githubusercontent.com/34022591/125246484-6eab9b00-e324-11eb-9827-e0973eb11016.png">

把你的RPC配置截图贴上来看看

**Comment by alexhua** [comment]
no response
