### ISSUE TITLE
V1.5.4 Download error, temp Revoke from web store

### ISSUE THREAD

**Issue by alexhua** [alexhua/Aria2-for-chrome#78]
a bug was found in v1.5.4 when getting cookies.

Temp solution: Enable "ask detail settings before download"

v1.5.5 is on the way.

**Comment by sirius422** [comment]
好耶，我晚上排查发现是插件的问题，准备来GitHub上下载旧版确认一下的，刚好看见这个issue 😂。

**Comment by alexhua** [comment]
> 好耶，我晚上排查发现是插件的问题，准备来GitHub上下载旧版确认一下的，刚好看见这个issue 😂。

好么，看来我发得挺及时。

**Comment by sirius422** [comment]
> > 好耶，我晚上排查发现是插件的问题，准备来GitHub上下载旧版确认一下的，刚好看见这个issue 😂。
> 
> 好么，看来我发得挺及时。

我还是反馈下情况吧，测试了几个网站，得到了1.5.4和1.5.3两个版本各种下载方式成功与否的表格。
无cookie使用[Vultr Looking Glass](https://lax-ca-us-ping.vultr.com/vultr.com.1000MB.bin)的1GB test文件为测试对象，需要cookie或者有其他限制的挑了三个测试对象（具体怎么个限制法我也没搞明白）
|   1.5.4  | 右键导出 | 拦截下载（不询问）| 拦截下载（询问） | 直接在AriaNG中新建任务 |
| ---- | ---- |
| 无cookie  |   ❌(400)  |  ✅  |  ✅  | ✅ |
| 115 |   ❌(400)  |  ✅  |  ❌(403)  | ❌(403) |
| 百度盘 | ❌(400) | ❌(403) | ✅ | ❌(403) |
| Java 8 | ❌(无报错，速度为0) | ✅ | ❌(Aria NG弹出但无反应) | ❌(重定向) |

|   1.5.3  | 右键导出 | 拦截下载（不询问）| 拦截下载（询问） | 直接在AriaNG中新建任务 |
| ---- | ---- |
| 无cookie  |  ✅  |  ✅  |  ✅  | ✅ |
| 115 |   ✅(403两次，但可下载)  |  ✅  |  ❌(403)  | ❌(403) |
| 百度盘 | ❌(400) | ❌(403) | ✅ | ❌(403) |
| Java 8 | ❌(重定向，下载了cgi) | ✅ | ✅ | ❌(重定向，下载了cgi) |
Aria的错误信息都和下面这条一样，只是最后的{错误代码}有所不同

    09/07 23:08:57 [ERROR] CUID#13 - Download aborted. URI=https://lax-ca-us-ping.vultr.com/vultr.com.1000MB.bin
    Exception: [AbstractCommand.cc:351] errorCode=22 URI=https://lax-ca-us-ping.vultr.com/vultr.com.1000MB.bin
      -> [HttpSkipResponseCommand.cc:240] errorCode=22 The response status is not successful. status={错误代码}

**Comment by alexhua** [comment]
测试很详细，很需要这样高质量的测试反馈。

**Comment by alexhua** [comment]
借这个机会说下各个下载方式的区别

附带信息 | 右键导出 | 拦截下载（不询问） | 拦截下载（询问） | 直接在AriaNG中新建任务
-- | -- | -- | -- | --
Cookies | ✅ | ✅ | ✅ | ❌（遵循aria2配置）
Referer | ✅ | ✅ | ✅| ❌（遵循aria2配置）
UserAgent | ✅ | ✅| ❌（遵循aria2配置） | ❌（遵循aria2配置）

**Comment by alexhua** [comment]
鉴于有些网站会检测UA（比如115），现在拦截下载（询问）时也带上UA。

最新：

附带信息 | 右键导出 | 拦截下载（不询问） | 拦截下载（询问） | 直接在AriaNG中新建任务
-- | -- | -- | -- | --
Cookies | ✅ | ✅ | ✅ | ❌（遵循aria2配置）
Referer | ✅ | ✅ | ✅ | ❌（遵循aria2配置）
UserAgent | ✅ | ✅ | ✅ | ❌（遵循aria2配置）

**Comment by alexhua** [comment]
@sirius422  v1.5.5已经发布了，有空的话再测一下。这次除了直接在AriaNG中新建任务，应该都能下了。如果没问题我就上架了。

**Comment by alexhua** [comment]
好的，辛苦了。下载单文件keepalive意义不大，有些网站加了反而出错，默认就不加了。新版已经提交审核。
