### ISSUE TITLE
Aria2 for Chrome在chrome商店显示404

### ISSUE THREAD

**Issue by f59375543** [alexhua/Aria2-for-chrome#79]
被下架了吗？

https://chrome.google.com/webstore/detail/mpkodccbngfoacfalldjimigbofkhgjn

**Comment by alexhua** [comment]
有bug，避免升级后受到影响，先下架了，请等待修复。

**Comment by f59375543** [comment]
> 有bug，避免升级后受到影响，先下架了，请等待修复。

我不慎升级到了1.5.4，现在它接管了我的所有下载，请问如何设置为我只有手动调用才能启动？

**Comment by think2011** [comment]
似乎我的自动升级后下载不了了，看记录是添加无效的一堆 undefined 的 cookie，等待更新
