### ISSUE TITLE
所有RPC配置同步到 AriaNg

### ISSUE THREAD

**Issue by xieliuhao** [alexhua/Aria2-for-chrome#80]
我有两个 RPC 配置，但我发现只会同步第一个配置到 AriaNg，能全同步到 AriaNg吗。

![image](https://user-images.githubusercontent.com/16849027/137088851-2b5814a2-5b70-415e-927e-979e21d8580c.png)
![image](https://user-images.githubusercontent.com/16849027/137088915-b1e9cc6f-bfa2-4ee2-8638-00090ead79fd.png)

**Comment by alexhua** [comment]
8b05c83

**Comment by xieliuhao** [comment]
good jop!
