### ISSUE TITLE
从浏览器截取下载时构建的自定义Header中的UA信息有问题

### ISSUE THREAD

**Issue by Mingx4211** [alexhua/Aria2-for-chrome#82]
从浏览器捕获下载时，自定义请求头中的UA字段拼写少了个“-”，导致无法正确导入UA信息
正常应该是
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36
但是用插件捕获时构建的自定义请求头UA字段少了个“-”，导致UA信息出错
UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36
Cookie:***

![Aria2c](https://user-images.githubusercontent.com/30297552/146762973-e3238411-7522-42ca-a754-0c2eadf49c5b.png)
![Snipaste_2021-12-20_19-47-03](https://user-images.githubusercontent.com/30297552/146763037-a280c6fb-c30a-4892-b67d-99ebb2d8891a.png)

**Comment by Mingx4211** [comment]
看了下应该是只有在开启了 “自动下载前询问参数设置” 选项的时候会出现这个问题，应该是构建Header的地方少打了个“-”

**Comment by alexhua** [comment]
> UserAgent

说得很对，感谢反馈。
