### ISSUE TITLE
Aria2 for Edge无法接管magnet协议

### ISSUE THREAD

**Issue by waingt** [alexhua/Aria2-for-chrome#83]
**Describe the bug**
在Edge浏览器上安装Aria2 for Edge扩展后，拦截不了magnet协议

**Expected behavior**
启用拦截磁力选项后，应该弹出一个“扩展想要打开magnet链接的提示”，但是没有

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Edge 96.0.1054.62
 - Version 1.5.5

**Additional context**
在Chrome上安装Aria2 for Chrome可以正常拦截
在Edge上安装Aria2 for Chrome也可以正常拦截（我现在是这样用的）

**Comment by alexhua** [comment]
edge版和chrome版代码是一套代码，只是改了个名字。
拦截magnet协议使用的是系统级调用，只能有一个默认处理程序，chrome或者edge只能二选一。

**Comment by alexhua** [comment]
如果需要通过Edge处理Magnet协议，需要在系统的默认应用里将Magnet的默认处理程序设置为Edge。
