### ISSUE TITLE
使用弹窗打开时，增加查看任务详情的支持

### ISSUE THREAD

**Issue by CCCAUCHY** [alexhua/Aria2-for-chrome#84]
使用新标签页或新窗口的设置时，有如图所示箭头可以查看任务详情，希望弹窗模式支持
![image](https://user-images.githubusercontent.com/55306290/148243251-d066e4ac-4cf0-4f25-8f18-bdf7a732cd27.png)
如果难以实现，建议在弹窗模式中增加按钮打开新标签页或新窗口，而不是每次都去设置里调

**Comment by alexhua** [comment]
#59
