### ISSUE TITLE
增加《右键导出下载前询问参数设置》的选项

### ISSUE THREAD

**Issue by snow212-cn** [alexhua/Aria2-for-chrome#86]
**Motivation**
Description of why you want add new feature. Ex. I'm always frustrated when [...]
右键导出Aria2 RPC时立即开始了下载，文件名都是乱的，设置中没有此选项，只有自动下载前询问

**Feature Description**
A clear and concise description of what this feature does.
* 设置中开启此选项后，右键导出Aria2 rpc时，不立即开始下载，先获取链接、打开新建任务参数界面（最好能同时自动获取链接文本作为文件名）
* ![chrome-extension___jjfgljkjddpcpfapejfkelkbjbehagbh_ui_ariang_index html](https://user-images.githubusercontent.com/18443918/154232465-2e6b9e0b-3e49-478f-914a-3d22415b391d.png)

**Is the solution code ready**
No

**Willing to maintain the related code in the future**
Yes

**Additional context**
Add any other context or screenshots to let common user know what this feature is.
![chrome-extension___jjfgljkjddpcpfapejfkelkbjbehagbh_options html](https://user-images.githubusercontent.com/18443918/154230776-30ddbfcd-79c6-4640-8c3f-c5ec747a74b7.png)

**Comment by alexhua** [comment]
这么设置的本意就是想右键短平快，实现快速导出下载。为什么不愿意通过拦截，跳转到详细设置呢？

**Comment by candrapersada** [comment]
for rename file download

**Comment by egoistinr** [comment]
文件名的部分不能像其他欄位一樣填入預設的名稱嗎
就一般下載時會得到的名稱
以我來說我是很少遇到需要重命名的情況
要去找原檔名反而多一道步驟
且有時候原下載頁面只有名稱不含副檔名還需要猜好幾個才打得開

**Comment by alexhua** [comment]
> 文件名的部分不能像其他欄位一樣填入預設的名稱嗎 就一般下載時會得到的名稱 以我來說我是很少遇到需要重命名的情況 要去找原檔名反而多一道步驟 且有時候原下載頁面只有名稱不含副檔名還需要猜好幾個才打得開

非必填栏目，如果想保留原文件名，空着就好。

**Comment by egoistinr** [comment]
> > 文件名的部分不能像其他欄位一樣填入預設的名稱嗎 就一般下載時會得到的名稱 以我來說我是很少遇到需要重命名的情況 要去找原檔名反而多一道步驟 且有時候原下載頁面只有名稱不含副檔名還需要猜好幾個才打得開
> 
> 非必填栏目，如果想保留原文件名，空着就好。

剛剛試了幾個印象中有問題的網站好像確實好了
有些是要過一段時間就會顯示正常的出來
另一個網站我剛剛去試原始下載檔名就是亂碼...
那應該我弄錯了不好意思
先前大概沒有等到顯示正常就刷掉重下了
連續幾次遇到問題後我後面都手動複製檔名沒發現
