### ISSUE TITLE
当使用非localhost作为第一RPC服务器时，无法正确拦截

### ISSUE THREAD

**Issue by dll233** [alexhua/Aria2-for-chrome#89]
**Describe the bug**
当使用非localhost作为第一RPC服务器时，无法正确拦截

**To Reproduce**
当使用非localhost作为第一RPC服务器时，无法正确拦截（使用了浏览器下载）
更改顺序（将localhost作为第一项）恢复正常，且2个RPC服务器均可正常使用
在ariaNg中2个服务器均可正常连接

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: win10pro
 - Browser chrome 99
 - Version aria 版本1.35

**Additional context**
似乎是将远程RPC服务器填入第一栏内，插件不能正确判断连接状态（但是点进插件自带的ariaNg页面显示成功连接），导致插件判定使用浏览器下载

**Comment by alexhua** [comment]
没有复现你的问题。

右击图标，打开“监测Aria2状态”能正常连接远程aria2吗？

方便的话请提供一下你的RPC服务器设置和连接失败时扩展背景页Devtool的网络 log
![chrome://extensions](https://user-images.githubusercontent.com/1220458/159699824-1752e877-278b-4fae-9c40-f0bdf7067016.png)

**Comment by dll233** [comment]
首先感谢您的回复！

我刚刚试了下我也复现不了了（真是玄学）

Q:右击图标，打开“监测Aria2状态”能正常连接远程aria2吗？
A:可以的，插件自带的ariaNg报告已连接（已经确认过是远程RPC服务器）

只能下次下次再连不上反馈日志给您了 ：）

**Comment by Dragon1573** [comment]
## 问题描述

Aria2 for Edge 无法正确拦截内置下载，插件图标状态监测与 Aria2NG 实际不符。

## 复现方式

1. 下载并安装 [Motrix v1.6.11](https://github.com/agalwood/Motrix/releases/tag/v1.6.11)
2. 启动 Motrix 并[开启 JSON-RPC 功能](https://github.com/agalwood/Motrix/wiki/RPC)，随机 Roll 一个访问密钥
3. 安装 Aria2 for Edge 插件
4. 在插件提供的 AriaNg 设置界面，添加 Motrix 的 JSON-RPC 作为唯一下载后端，RPC 地址应为 `ws://localhost:16800/jsonrpc` ，填写第2步 Roll 出的密钥
5. 刷新 AriaNg 界面，Aria2 状态显示 **已连接** ，版本为 `v1.35.0` ，图标仍显示 "Failed to connect with Aria2."

![image](https://user-images.githubusercontent.com/49941141/215272152-3a0db4ab-819b-40ec-a220-bcc24eb00737.png)

![image](https://user-images.githubusercontent.com/49941141/215272119-b5a1b641-1178-498d-b6a6-0c531d320a9d.png)

## 初步定位

Motrix 开放的 JSON-RPC 端口号为 `16800` 而非 Aria2 默认的 `6800` ，Aria2 for Edge 插件后台仍持续使用 `6800` 作为 RPC 端口进行状态监测，没有按照 AriaNg 设置界面将端口切换为 `16800` 。

![image](https://user-images.githubusercontent.com/49941141/215272410-ff59633a-59d2-4973-95e8-a01fc41b27be.png)

*****

希望 @alexhua 可以提供相关文档指导修复此问题，谢谢。

**Comment by alexhua** [comment]
@Dragon1573 AriaNG的设置和扩展的设置是相对独立的。去扩展的选项配置页面改Aria2-RPC-Server 的URL地址。

**Comment by Dragon1573** [comment]
> AriaNG的设置和扩展的设置是相对独立的。

原来如此，我说这俩怎么请求的地址是不一样的🤣

> 去扩展的选项配置页面改 `Aria2-RPC-Server` 的 URL 地址。

多谢，现在修改后，图标状态就正确了。:heart:

![image](https://user-images.githubusercontent.com/49941141/215273147-ee1a8bff-5c57-4eb6-9642-a8b4194e2a0e.png)

**Comment by RoyRao2333** [comment]
@alexhua 

不好意思来挖个坟，刚好借助 @Dragon1573  的提问

之前配置成功过Motrix，后面手贱删了Motrix，再次安装后无法配置成功了

<img width="504" alt="image" src="https://github.com/user-attachments/assets/97af684f-846e-428a-bbd0-23c836084f46">

<img width="1084" alt="image" src="https://github.com/user-attachments/assets/d14d2857-eeb1-473b-a6e2-072e4f33933e">

<img width="1581" alt="image" src="https://github.com/user-attachments/assets/7e64f41e-2350-4074-a88c-2745c4cee8d5">

<img width="478" alt="image" src="https://github.com/user-attachments/assets/8c34746f-1b48-4887-a7c0-e8b26721de17">

我这边请求确实是16800端口，但是设置了相同的secret后，返回`
{"id":"xxxx","jsonrpc":"2.0","error":{"code":1,"message":"Unauthorized"}}`

请问该如何解决这个呢？感谢！
