### ISSUE TITLE
【建议】第一次配置AriaNg，RPC地址应该默认本地地址

### ISSUE THREAD

**Issue by zhuxt2015** [alexhua/Aria2-for-chrome#9]
第一次配置AriaNg，由于地址不对，页面长时间的处于加载中，如果初始化RPC地址默认为http://127.0.0.1:6800/jsonrpc，就不会出现这种情况了
![image](https://user-images.githubusercontent.com/13765310/61172128-f2561400-a5b2-11e9-9022-d34b54357a05.png)

**Comment by alexhua** [comment]
好的，下个版本改进下。

**Comment by alexhua** [comment]
Done
25a843e0ac62d10a3e0adc28967cb6916b98d8aa
