### ISSUE TITLE
How do I build this repo so it can be loaded as an unpacked extension

### ISSUE THREAD

**Issue by pingshunhuangalex** [alexhua/Aria2-for-chrome#90]
Hi there,

I've been maintaining a similar extension that leverages YAAW and AriaNg. I'm glad to find a kindred spirit who's been diligent in pushing the downloading experience to the next level.

Just wondering how I can build your repo to generate an unpacked extension so I can dabble in this further. It'd be nice if a series of steps can be documented. Thanks.

**Comment by alexhua** [comment]
To keep it simple, I made this extension as a buildless project. You could just load it from soure code in chrome after deleting un-related github files: "_config.yml".  If you're familar with chrome extension development, it will be very easy for you to get invovled.

**Comment by pingshunhuangalex** [comment]
Cool beans. Thanks mate.

**Comment by pingshunhuangalex** [comment]
BTW, what does `_config.yml` do then if it's not part of the build-less project? Thanks.

**Comment by alexhua** [comment]
> github files: "_config.yml"

You can get answer from my last reply. 🙃

**Comment by pingshunhuangalex** [comment]
Right, site generator configs for GitHub Pages. 👌
