### ISSUE TITLE
Can we have a "download capture only" extension?

### ISSUE THREAD

**Issue by Livy-Inverse** [alexhua/Aria2-for-chrome#91]
As with Unix philosophy "do one thing and do it well", I would like to ask if we can have a Chrome extension which only capture download links and send them to the AriaNG server? I mean we have 3 different things:

1. aria2c running in RPC mode on one server
2. AriaNG running in another server, which acts as a front-end for aria2 server
3. Chrome extensions on various client PCs, which captures the link and and send them to the AriaNG server

Of course we can combine all of them on a single PC. But personally, I think it would be better to split their functionalities into different components. The obvious benefit would be upgrading AriaNG independently of the extension.

**Comment by alexhua** [comment]
No, we dont.

According to my experience, common end user always likes all-in-one application whose philosophy is different from operation system module design. 
And as current condition,  you can use aria2, ariaNG, extension separatly since you know how to config.

Thanks for you advice.

**Comment by Livy-Inverse** [comment]
I just realized `Aria2 for Chrome` does not rely on `AriaNG` to work. It has its own configuration parameters, and can send download links directly to `aria2`. `AriaNG` works as a "viewer" most of the time.

You're right. I think I can install another web interface such as [WebUI-Aria2](https://ziahamza.github.io/webui-aria2/) and it will work just fine as another viewer. It is nice to have two GUIs at once.

**Comment by alexhua** [comment]
Yes. You got it.
