### ISSUE TITLE
Saving settings in browser DB or browser storage

### ISSUE THREAD

**Issue by nimagp** [alexhua/Aria2-for-chrome#92]
**Motivation**
It's really annoying that every time I restart browser or turn off/on aria2, setting resets(I mean Download location, opening popup etc) 
**Feature Description**
A clear and concise description of what this feature does.
* This feature saves settings to browser storage (as settings is saved in json format, a for loop should be fine according to this [documentation](https://developer.chrome.com/docs/extensions/reference/storage/)) , and imports it every time browser starts or connection to aria2 changes.
* Using this way, makes automated syncing settings(on settings changing) more easy.

**Is the solution code ready**
No

**Willing to maintain the related code in the future**
No 

**Additional context**

**Comment by alexhua** [comment]
Our extension could save all user's setting in to browser local storage and sync it between user's devices via google account.
So I consider it is the un-proper use or browser settings cause your problem.
My advice: Reset your chrome settings to default .
