### ISSUE TITLE
能否将文件校验值传递给aria2

### ISSUE THREAD

**Issue by waingt** [alexhua/Aria2-for-chrome#93]
**Motivation**
下载后手动检验校验值太过麻烦

**Feature Description**
A clear and concise description of what this feature does.
如果有个类似 #35 提到的交互式对话框, 希望能加入一个提供文件校验值(MD5, SHA-1)的选项, 并传递给aria2

**Is the solution code ready**
No

**Willing to maintain the related code in the future**
No

**Additional context**
Add any other context or screenshots to let common user know what this feature is.

**Comment by alexhua** [comment]
最新版AriaNG已经支持在新建任务时设置“校验和”选项，打开扩展的“下扩展载前询问详细参数”即可。
ed638e72aa589982a37fa0fd2f1bb063cb86fb07
