### ISSUE TITLE
希望捕获下载后，浏览器图标上给个标识

### ISSUE THREAD

**Issue by brucmao** [alexhua/Aria2-for-chrome#94]
希望增加功能，点击下载后，浏览器图标上有相应的标识，经常出现点击下载没反应，于是反复点击多次链接出现重复下载的情况，其实aria2已经在后台开始下载了。或者aria2捕获到下载后给个提示

以前用过一个相似插件，点击下载后的有个提示，感觉挺好的
https://github.com/jae-jae/Camtd

![This is an image](https://camo.githubusercontent.com/011ac748963f6341a4107df89b853dbeacc2bf796fdd1a2b8527e865a6416736/68747470733a2f2f63646e2e7261776769742e636f6d2f6a61652d6a61652f5f7265736f75726365732f6d61737465722f70616e2e676966)

**Comment by alexhua** [comment]
希望你熟悉扩展的大部分功能后再来提需求。
