### ISSUE TITLE
The extension does not recognize --rpc-secret token or HTTPS connection properly

### ISSUE THREAD

**Issue by fnfontana** [alexhua/Aria2-for-chrome#95]
**Describe the bug**
After enable the option `--rpc-secret` and fill up the correspondent "Aria2 RPC Secret Token" field and/or enable HTTPS using the options `--rpc-certificate`; `--rpc-private-key`; `--rpc-secure`; the AriaNg connects and even can download files, but the 'Download Capture' feature does not work, so it's needed to manually add the download links and the error message 'Failed to connect with Aria2. Reason:Unauthorized' is displayed on the extension icon, which also displays a red letter 'E' meaning "Error". 

**To Reproduce**
1. Start aria2c.exe with the parameter `--rpc-secret='security-token'` or add it to `aria2.conf` file. 
2. Add the same security-token to AriaNg
3. It will connect, and even can download files… 
4. But displays the error message, the download capture feature does not work properly and downloads must be manually added and the red letter 'E' is displayed on the extension icon. 

The steps to reproduce the related to HTTPS connection error are the same, just add to `aria2.conf` file:
- `rpc-certificate=${HOME}/.aria2//certs/ariarpc.p12`
- `rpc-secure=true`
Then go to AriaNg and replaces HTTP for HTTPS, then restart it. 

It will connect, but the same error message will be displayed. Also, the download capture feature does not work. 

**Expected behavior**
After passes the --rpc-secret=<my_security_token> option to aria2c.exe when launching the RPC server and add the correspondent secret token to AriaNg, is expected to work normally and with security enforced. Also, when using HTTPS instead of just HTTP.

**Screenshots**
![image](https://user-images.githubusercontent.com/8870142/171521075-a7bb3f47-ac11-42b8-9fe1-dad0111badc0.png)
![image](https://user-images.githubusercontent.com/8870142/171518077-a7c48a73-2164-423c-94d6-0167cef9db34.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro 21H2 19044.1706
 - Browser: Chrome
 - Version: 102.0.5005.63; 64 bits

**Additional context**
I don't know if using HTTPS in that case makes sense, because aria2c.exe it's running on my Desktop PC (localhost). But I also have a NAS and want to run aria2c rpc server on there in the future, that's the reason I'm trying to make HTTPS connection to localhost.

**Comment by alexhua** [comment]
AriaNG settings and extension capture function settings are independent.
Capture function should also work with HTTPS protocol and secret key option after setting in extension option page correctly.
"Reason:Unauthorized" means that secret key is not set correctly.
![image](https://user-images.githubusercontent.com/1220458/171550130-d26971f9-c598-403f-a7c9-fe61db332707.png)
 Would you please check it again?

**Comment by fnfontana** [comment]
> AriaNG settings and extension capture function settings are independent.
> Capture function should also work with HTTPS protocol and secret key option after setting in extension option page correctly.
> "Reason:Unauthorized" means that secret key is not set correctly.
> ![image](https://user-images.githubusercontent.com/1220458/171550130-d26971f9-c598-403f-a7c9-fe61db332707.png)
>  Would you please check it again?

Thank you! I didn't have seen before the extension options page. Now it's working fine with --rpc-secret and HTTPS enabled.
