### ISSUE TITLE
如何取消扩展的磁力拦截功能

### ISSUE THREAD

**Issue by sq9960** [alexhua/Aria2-for-chrome#98]
现在浏览器地址栏打开磁力链接一直被拦截，无法打开迅雷，扩展删除了也只是显示扩展被屏蔽

**Comment by alexhua** [comment]
如果扩展还在，去扩展选项页面，取消勾选“拦截磁力链接”。
如果已经卸载：地址栏输入 chrome://settings/handlers 移除扩展
![image](https://user-images.githubusercontent.com/1220458/180913385-120bfc39-66cf-4f50-86f6-591a761b2c3e.png)


如果想通过迅雷打开磁力链接，请在迅雷中查找相关设置选项，将迅雷设置为磁力链接默认处理程序。

**Comment by sq9960** [comment]
已经删除了，但是删除之后无法指定magnet协议用迅雷打开了，在系统设置里找不到迅雷

**Comment by alexhua** [comment]
> 已经删除了，但是删除之后无法指定magnet协议用迅雷打开了，在系统设置里找不到迅雷

已经超出问题范围了，在迅雷里找找怎么设置吧，或者重新安装迅雷试试。

**Comment by sq9960** [comment]
搞定了，还是改了注册表才弄好的，感谢了

**Comment by shrderek** [comment]
> 搞定了，还是改了注册表才弄好的，感谢了

教一下，我试了改注册表还是没成功

**Comment by shaojs321** [comment]
试试这个
[](https://cf.tonyshao.cf/file/b89fd687ff141815de826.png)

**Comment by shaojs321** [comment]
试试这个
[](https://cf.tonyshao.cf/file/b89fd687ff141815de826.png)

**Comment by shaojs321** [comment]
试试这个
<img width="703" alt="Snipaste_2023-01-31_11-43-29" src="https://user-images.githubusercontent.com/56724141/215658140-90f28f1c-97b9-4509-874f-f712e4a02416.png">
<img width="688" alt="Snipaste_2023-01-31_11-43-55" src="https://user-images.githubusercontent.com/56724141/215658144-57708c0d-6533-492d-8575-cf50c0309e92.png">

**Comment by alexhua** [comment]
> > 搞定了，还是改了注册表才弄好的，感谢了
> 
> 教一下，我试了改注册表还是没成功

Windows下，要彻底清除Magnet协议与Chrome或Edge的关联，可以在注册表中删除下面两项:
`\HKEY_CLASSES_ROOT\magnet`
`\HKEY_CURRENT_USER\Software\Microsoft\Windows\Shell\Associations\UrlAssociations\magnet`

**Comment by Kp31-Somi** [comment]
EDGE浏览器删除这个里面的MAGNET值
`\HKEY_LOCAL_MACHINE\SOFTWARE\Clients\StartMenuInternet\Microsoft Edge\Capabilities\URLAssociations`

**Comment by calloftimereiver** [comment]
> > > 搞定了，还是改了注册表才弄好的，感谢了
> > 
> > 
> > 教一下，我试了改注册表还是没成功
> 
> Windows下，要彻底清除Magnet协议与Chrome或Edge的关联，可以在注册表中删除下面两项: `\HKEY_CLASSES_ROOT\magnet` `\HKEY_CURRENT_USER\Software\Microsoft\Windows\Shell\Associations\UrlAssociations\magnet`

解决了，非常感谢
